"""Initial catalogue; saved owner edits take precedence."""
PROJECTS = [
    {"id":"bidblitz","name":"BidBlitz","description":"Super App & Haupt-Admin","url":"/admin","admin_url":"/admin","status":"connected","sso":True},
    {"id":"eyes","name":"Eyes.BidBlitz","description":"Face Search","url":"https://eyes.bidblitz.ae","admin_url":"https://eyes.bidblitz.ae","status":"online","sso":False},
    {"id":"trade","name":"Trade BidBlitz","description":"Trading Dashboard","url":"https://trade.bidblitz.ae","admin_url":"https://trade.bidblitz.ae","status":"online","sso":False},
    {"id":"nex","name":"BidBlitz NEX","description":"AI Workflow Plattform","url":"https://nex.bidblitz.ae","admin_url":"https://nex.bidblitz.ae","status":"online","sso":False},
    {"id":"stack","name":"BidBlitz Stack","description":"Infrastruktur & Developer Stack","url":"https://stack.bidblitz.ae","admin_url":"https://stack.bidblitz.ae","status":"dev","sso":False},
    {"id":"aion","name":"AION","description":"KI-Assistent & Brain","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"power","name":"Power BidBlitz","description":"Powerbank Sharing","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"charging","name":"iCharging","description":"Ladeinfrastruktur & Elektromobilität; getrennt von BidBlitz Charge","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"verify","name":"BidBlitz Verify","description":"Identitätsprüfung","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"passport","name":"BidBlitz Passport","description":"Digital Product Passport","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"games","name":"Game.BidBlitz","description":"Games Plattform; bestehender BidBlitz-Adminbereich","url":None,"admin_url":"/admin/game-settings","status":"connected","sso":True},
    {"id":"iptv","name":"BidBlitz IPTV","description":"TV & Streaming Plattform","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"the-eye","name":"The Eye","description":"Global Intelligence Dashboard","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"veysca","name":"VEYSCA","description":"Security & Web Risk","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"conformexa","name":"Conformexa","description":"EU Compliance","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"os","name":"BidBlitz OS","description":"AI Operating System; Builder ist ein Modul dieses Projekts","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"remote","name":"Remote","description":"Eigenständige Remote-AI-Plattform; Geräte, Freigaben und AI-Sitzungen","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"spy","name":"Spy BidBlitz","description":"Geräte- und Familiensicherheit; früher BidBlitz Device, inklusive Kids Control","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"tv","name":"BidBlitz TV","description":"Android-TV-Player für eigene berechtigte Playlists; früher AK Stream TV","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"charge","name":"BidBlitz Charge","description":"Ladezubehör, Handel & Franchise; getrennt von iCharging","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"bidtax","name":"BIDTAX","description":"Steuer- und Buchhaltungssoftware; eigenes Super-Admin-System","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"match","name":"BidBlitz Match","description":"Separates gespeichertes Quellcode-Projekt; zentrale Anmeldung noch nicht geprüft","url":None,"admin_url":None,"status":"pending","sso":False},
    {"id":"pay","name":"BidBlitz Pay","description":"Zahlungen, Wallet und Pay-Anträge in der BidBlitz-App","url":"/admin/payments","admin_url":"/admin/payments","status":"connected","sso":True},
    {"id":"staff","name":"BidBlitz Staff","description":"Personal, Manager und Enterprise in der BidBlitz-App","url":"/admin/employees","admin_url":"/admin/employees","status":"connected","sso":True},
    {"id":"identity","name":"BidBlitz ID","description":"Konten, Rollen und Anmeldung in der BidBlitz-App","url":"/admin/manage","admin_url":"/admin/manage","status":"connected","sso":True},
    {"id":"taxi","name":"BidBlitz Taxi","description":"Taxi-Fleet, Fahrer und Mobility-Tarife in der BidBlitz-App","url":"/admin/taxi","admin_url":"/admin/taxi","status":"connected","sso":True},
    {"id":"scooter","name":"BidBlitz Scooter","description":"Scooter-Fleet und Abonnements in der BidBlitz-App","url":"/admin/scooter-fleet","admin_url":"/admin/scooter-fleet","status":"connected","sso":True},
    {"id":"food","name":"BidBlitz Food","description":"Restaurants und QR-Tische in der BidBlitz-App","url":"/admin/restaurants","admin_url":"/admin/restaurants","status":"connected","sso":True},
    {"id":"auctions","name":"BidBlitz Auctions","description":"Produkte, Auktionen und Gewinner in der BidBlitz-App","url":"/admin/auctions","admin_url":"/admin/auctions","status":"connected","sso":True},
    {"id":"merchant","name":"BidBlitz Merchant / POS","description":"Händler, Onboarding und Abrechnungen in der BidBlitz-App","url":"/admin/merchants","admin_url":"/admin/merchants","status":"connected","sso":True},
    {"id":"pool","name":"BidBlitz Pool","description":"Schwimmbad- und Ticketverwaltung in der BidBlitz-App","url":"/admin/pool","admin_url":"/admin/pool","status":"connected","sso":True},
    {"id":"tickets","name":"BidBlitz Audi Tickets","description":"Ticket-System in der BidBlitz-App","url":"/admin/audi-ticket-system","admin_url":"/admin/audi-ticket-system","status":"connected","sso":True},
    {"id":"car-rental","name":"BidBlitz Car Rental","description":"Mietwagen und Streitfälle in der BidBlitz-App","url":"/car-rental/admin","admin_url":"/car-rental/admin","status":"connected","sso":True},
    {"id":"mining","name":"BidBlitz Mining","description":"Mining-Trust-Verwaltung in der BidBlitz-App; keine Freigabe für echte Transaktionen","url":"/mining-trust-admin","admin_url":"/mining-trust-admin","status":"connected","sso":True},
    {"id":"ev","name":"BidBlitz EV","description":"Vorhandene EV-Verwaltung: Betreiber, Hardware, Tarife und Auszahlungen; separate API-Rechte bleiben wirksam","url":"/admin/ev","admin_url":"/admin/ev","status":"connected","sso":True},
]
