export const ADMIN_TAB_MAP = {
  users: "users",
  customers: "users",
  enterprise: "users",
  kyc: "verification",
  managers: "roles",
  employees: "roles",
  influencer: "roles",
  "auto-ads": "promos",
  "partner-credit": "merchant-fees",
  merchants: "merchants",
  partners: "merchants",
  "partner-portal": "merchants",
  applications: "merchants",
  products: "auctions",
  auctions: "auctions",
  bot: "auctions",
  winners: "auctions",
  "standard-auctions": "auctions",
  "vip-auctions": "auctions",
  "voucher-auctions": "auctions",
  "bot-system": "auctions",
  "winner-control": "auctions",
  analytics: "analytics",
  "product-analysis": "analytics",
  "product-stats": "analytics",
  "user-analysis": "analytics",
  "user-stats": "analytics",
  "revenue-analysis": "analytics",
  "customer-intelligence": "customer-intelligence",
  "customer-map": "customer-intelligence",
  "pay-requests": "pay-requests",
  payouts: "payouts",
  wise: "payouts",
  "qr-management": "qr-management",
  pool: "pool",
  "biopay-audit": "biopay-audit",
  coupons: "promos",
  "merchant-coupons": "promos",
  "bidder-coupons": "promos",
  "partner-coupons": "promos",
  "discount-codes": "promos",
  discounts: "promos",
  marketing: "promos",
  "email-marketing": "promos",
  finance: "transactions",
  transactions: "transactions",
  topup: "transactions",
  deposits: "transactions",
  withdrawals: "transactions",
  fees: "merchant-fees",
  compliance: "verification",
  moderation: "verification",
  logs: "audit",
  debug: "audit",
  rtk: "settings",
  system: "settings",
  maintenance: "settings",
  cms: "settings",
  "game-settings": "settings",
  passwords: "settings",
  database: "settings",
  sustainability: "flags",
  health: "flags",
  settings: "settings",
};

export function getAdminTabFromPath(currentPath) {
  const slug = (currentPath || "").replace("/admin/", "");
  return ADMIN_TAB_MAP[slug] || "overview";
}