export const ADMIN_TAB_MAP = {
  users: "users",
  customers: "users",
  enterprise: "users",
  kyc: "verification",
  managers: "roles",
  employees: "roles",
  influencer: "roles",
  "auto-ads": "promos",
  "partner-credit": "merchant-fees",
  merchants: "merchants",
  "partner-portal": "merchants",
  applications: "merchants",
  products: "auctions",
  "standard-auctions": "auctions",
  "vip-auctions": "auctions",
  "voucher-auctions": "auctions",
  "bot-system": "auctions",
  "winner-control": "auctions",
  analytics: "analytics",
  "product-analysis": "analytics",
  "user-analysis": "analytics",
  "revenue-analysis": "analytics",
  "customer-intelligence": "customer-intelligence",
  "customer-map": "customer-intelligence",
  "pay-requests": "pay-requests",
  payouts: "payouts",
  "qr-management": "qr-management",
  pool: "pool",
  "biopay-audit": "biopay-audit",
  "merchant-coupons": "promos",
  "bidder-coupons": "promos",
  "partner-coupons": "promos",
  "discount-codes": "promos",
  marketing: "promos",
  "email-marketing": "promos",
  finance: "transactions",
  transactions: "transactions",
  deposits: "transactions",
  withdrawals: "transactions",
  fees: "merchant-fees",
  compliance: "verification",
  moderation: "verification",
  logs: "logs",
  rtk: "settings",
  system: "settings",
  settings: "settings",
};

export function getAdminTabFromPath(currentPath) {
  const slug = (currentPath || "").replace("/admin/", "");
  return ADMIN_TAB_MAP[slug] || "overview";
}