"""
BidBlitz Staff — Offline Sync Queue for Clock Events
=======================================================
Mitarbeiter können offline stempeln (Untergeschoss, Tunnel, Lager).
Lokal gespeicherte Events werden beim nächsten Online-Status hochgesynct.

Idempotency:
  - Client generiert UUID `client_event_id`. Server prüft, ob dieselbe ID
    bereits in `staff_clock_events` existiert → skip insert, return existing.
  - So kann Client beliebig oft retryen ohne Duplikate.

Endpoints:
  POST /api/staff/clock/sync  — Batch-Sync (max 100 events per call)
  GET  /api/staff/clock/sync/status — last_sync_at + queue meta (debugging)
"""
from datetime import datetime, timezone
from typing import List, Literal, Optional
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel, Field
from uuid import uuid4
from core.database import db
from routes.staff import get_staff_from_session

router = APIRouter(prefix="/api/staff/clock", tags=["staff-clock-offline"])


class OfflineClockEvent(BaseModel):
    client_event_id: str = Field(..., min_length=8, max_length=64,
                                 description="UUID generated by client at event time")
    action: Literal["clock_in", "clock_out", "break_start", "break_end"]
    captured_at: str = Field(..., description="ISO datetime when user tapped (NOT now)")
    lat: Optional[float] = None
    lng: Optional[float] = None
    accuracy_m: Optional[float] = None
    note: Optional[str] = Field(None, max_length=500)
    customer: Optional[str] = Field(None, max_length=200)
    equipment: Optional[str] = Field(None, max_length=120)
    kilometers: Optional[float] = None
    project: Optional[str] = Field(None, max_length=120)
    photo_url: Optional[str] = Field(None, max_length=1024)
    geofence_id: Optional[str] = None
    source: Optional[str] = "offline_sync"
    device_type: Optional[str] = None
    platform: Optional[str] = None
    app_version: Optional[str] = None


class OfflineSyncBatch(BaseModel):
    events: List[OfflineClockEvent] = Field(..., min_items=1, max_items=100)


@router.post("/sync")
async def sync_offline_events(batch: OfflineSyncBatch, staff=Depends(get_staff_from_session)):
    """Sync offline-captured clock events. Idempotent via client_event_id."""
    results: List[dict] = []
    sorted_events = sorted(batch.events, key=lambda e: e.captured_at)

    for ev in sorted_events:
        existing = await db.staff_clock_events.find_one(
            {"client_event_id": ev.client_event_id, "staff_id": staff["id"]},
            {"_id": 0, "id": 1},
        )
        if existing:
            results.append({"client_event_id": ev.client_event_id, "status": "duplicate", "id": existing["id"]})
            continue

        doc = {
            "id": str(uuid4()),
            "client_event_id": ev.client_event_id,
            "merchant_id": staff["merchant_id"],
            "staff_id": staff["id"],
            "action": ev.action,
            "timestamp": ev.captured_at,         # preserve original capture time
            "synced_at": datetime.now(timezone.utc).isoformat(),
            "lat": ev.lat,
            "lng": ev.lng,
            "accuracy_m": ev.accuracy_m,
            "note": ev.note,
            "customer": ev.customer,
            "equipment": ev.equipment,
            "kilometers": ev.kilometers,
            "project": ev.project,
            "photo_url": ev.photo_url,
            "geofence_id": ev.geofence_id,
            "source": ev.source or "offline_sync",
            "device_type": ev.device_type,
            "platform": ev.platform,
            "app_version": ev.app_version,
            "offline_captured": True,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.staff_clock_events.insert_one(doc)

        # Update sync meta
        await db.staff_offline_sync_meta.update_one(
            {"staff_id": staff["id"]},
            {"$set": {"last_sync_at": doc["synced_at"]}, "$inc": {"total_synced": 1}},
            upsert=True,
        )
        results.append({"client_event_id": ev.client_event_id, "status": "synced", "id": doc["id"]})

    synced = sum(1 for r in results if r["status"] == "synced")
    dup = sum(1 for r in results if r["status"] == "duplicate")
    return {
        "success": True,
        "synced": synced,
        "duplicates": dup,
        "total": len(results),
        "results": results,
    }


@router.get("/sync/status")
async def sync_status(staff=Depends(get_staff_from_session)):
    """Returns last successful sync timestamp + count for the current staff."""
    meta = await db.staff_offline_sync_meta.find_one({"staff_id": staff["id"]}, {"_id": 0}) or {}
    offline_count = await db.staff_clock_events.count_documents({
        "staff_id": staff["id"], "offline_captured": True,
    })
    return {
        "last_sync_at": meta.get("last_sync_at"),
        "total_synced": meta.get("total_synced", 0),
        "offline_events_persisted": offline_count,
        "server_time": datetime.now(timezone.utc).isoformat(),
    }
