const COPY = {
  de: {
    cashierTitle: "Kasse",
    cashierSubtitle: "Alles für den nächsten Verkauf — ohne Ablenkung.",
    ownerTitle: "Owner Übersicht",
    ownerSubtitle: "Heute wichtige Zahlen und die schnellsten Aktionen.",
    managerTitle: "Manager Übersicht",
    managerSubtitle: "Offene Schichten, Probleme und Freigaben zuerst.",
    employee: "Mitarbeiter",
    branch: "Filiale",
    register: "Kasse",
    connection: "Verbindung",
    online: "Online",
    offline: "Offline",
    terminalDisconnected: "Terminal nicht verbunden",
    printerDisconnected: "Drucker nicht verbunden",
    searchPlaceholder: "Produkt, Barcode, SKU oder Kategorie suchen",
    barcodePlaceholder: "Barcode scannen oder eingeben",
    categories: "Kategorien",
    favourites: "Favoriten",
    recent: "Zuletzt genutzt",
    noProducts: "Kein Produkt gefunden.",
    scanAgain: "Barcode erneut scannen",
    searchManually: "Produkt manuell suchen",
    addProduct: "Produkt hinzufügen",
    cart: "Warenkorb",
    cartEmpty: "Noch keine Artikel im Warenkorb.",
    cartHint: "Tippe auf ein Produkt, um den Verkauf zu starten.",
    total: "Gesamt",
    subtotal: "Zwischensumme",
    discount: "Rabatt",
    tax: "Steuer",
    pay: "Bezahlen",
    viewCart: "Warenkorb",
    newSale: "Neuer Verkauf",
    customerDisplay: "Customer Display",
    sales: "Verkäufe",
    hardware: "Hardware",
    help: "Hilfe",
    training: "Kurztraining",
    choosePayment: "Bitte Zahlungsmittel auswählen",
    holdCard: "Bitte Karte oder Smartphone an das Gerät halten",
    processing: "Zahlung wird verarbeitet",
    success: "Zahlung erfolgreich",
    declined: "Zahlung wurde abgelehnt",
    connectionLost: "Verbindung unterbrochen",
    reviewing: "Zahlungsstatus wird geprüft",
    doNotRepay: "Bitte nicht erneut bezahlen.",
    thankYou: "Vielen Dank für deinen Einkauf.",
    failedTitle: "Zahlung nicht erfolgreich",
    failedText: "Die Zahlung wurde nicht abgeschlossen.",
    retry: "Erneut versuchen",
    otherMethod: "Andere Zahlungsmethode",
    cancel: "Abbrechen",
    checkStatus: "Status prüfen",
    callManager: "Manager rufen",
    unavailable: "Noch nicht aktiviert",
    active: "Aktiv",
    lowStock: "Wenig Bestand",
    outOfStock: "Ausverkauft",
    variant: "Varianten",
    promo: "Promo",
    paperReceipt: "Papierbeleg",
    emailReceipt: "E-Mail",
    qrReceipt: "QR-Code",
    noReceipt: "Kein Beleg",
    print: "Drucken",
    email: "E-Mail",
    receiptNumber: "Belegnummer",
    amount: "Betrag",
    paymentMethod: "Zahlungsmethode",
    roleCashier: "Kassierer",
    roleManager: "Manager",
    roleOwner: "Eigentümer",
    startSale: "Wie starte ich einen Verkauf?",
    removeItem: "Wie storniere ich einen Artikel?",
    printReceipt: "Wie drucke ich einen Beleg?",
    declinedHelp: "Was mache ich bei abgelehnter Zahlung?",
    trainingStep1: "Produkt auswählen",
    trainingStep2: "Warenkorb prüfen",
    trainingStep3: "Bezahlen",
    trainingStep4: "Zahlungsmethode wählen",
    trainingStep5: "Neuer Verkauf",
    skip: "Überspringen",
    replayLater: "Später erneut zeigen",
    completed: "Verstanden",
    quickActions: "Schnellzugriffe",
    ownerMetricRevenue: "Umsatz heute",
    ownerMetricSales: "Verkäufe heute",
    ownerMetricPayouts: "Offene Auszahlungen",
    ownerMetricStock: "Niedriger Lagerbestand",
    ownerMetricDevices: "Geräteprobleme",
    ownerMetricTasks: "Offene Aufgaben",
    managerMetricShifts: "Offene Schichten",
    managerMetricRefunds: "Rückerstattungen",
    managerMetricDevice: "Geräteprobleme",
    managerMetricStock: "Lagerwarnungen",
    managerMetricRevenue: "Tagesumsatz",
    actionOpenPos: "Kasse öffnen",
    actionAddProduct: "Produkt hinzufügen",
    actionInviteStaff: "Mitarbeiter einladen",
    actionViewReport: "Bericht ansehen",
    actionFindSale: "Verkauf suchen",
    actionReviewRefunds: "Rückerstattung prüfen",
    actionReviewShift: "Schicht prüfen",
    cashDescription: "Sofort abschließen und Rückgeld berechnen",
    cardDescription: "Karte oder Smartphone an das Terminal halten",
    walletDescription: "Per QR-Code oder BidBlitz-ID bezahlen",
    qrDescription: "Kunde scannt den QR-Code am Display",
    voucherDescription: "Gutschein einlösen oder verrechnen",
    invoiceDescription: "Später bezahlen nach Freigabe",
    tapToPayDescription: "Nur mit zertifiziertem Provider",
    statusAnnouncement: "Aktueller Zahlungsstatus",
    cartLocked: "Warenkorb ist während einer offenen Zahlung gesperrt.",
    statusRefreshed: "Zahlungsstatus aktualisiert.",
    customerReady: "Bitte Zahlungsmittel auswählen",
    hardwareHint: "Detaillierte Diagnose nur unter /merchant/pos/hardware",
    mockedEmail: "E-Mail-Beleg wird im nächsten Schritt angeschlossen.",
    qty: "Menge",
    products: "Produkte",
  },
  en: {
    cashierTitle: "Checkout",
    cashierSubtitle: "Everything for the next sale — nothing extra.",
    ownerTitle: "Owner overview",
    ownerSubtitle: "Today’s key numbers and the fastest actions.",
    managerTitle: "Manager overview",
    managerSubtitle: "Open shifts, issues and approvals first.",
    employee: "Employee",
    branch: "Branch",
    register: "Register",
    connection: "Connection",
    online: "Online",
    offline: "Offline",
    terminalDisconnected: "Terminal disconnected",
    printerDisconnected: "Printer disconnected",
    searchPlaceholder: "Search product, barcode, SKU or category",
    barcodePlaceholder: "Scan or enter barcode",
    categories: "Categories",
    favourites: "Favourites",
    recent: "Recent",
    noProducts: "No product found.",
    scanAgain: "Scan barcode again",
    searchManually: "Search manually",
    addProduct: "Add product",
    cart: "Cart",
    cartEmpty: "No items in the cart yet.",
    cartHint: "Tap a product to start the sale.",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    pay: "Pay",
    viewCart: "Cart",
    newSale: "New sale",
    customerDisplay: "Customer display",
    sales: "Sales",
    hardware: "Hardware",
    help: "Help",
    training: "Quick training",
    choosePayment: "Please choose a payment method",
    holdCard: "Please hold card or phone to the terminal",
    processing: "Payment is processing",
    success: "Payment successful",
    declined: "Payment was declined",
    connectionLost: "Connection interrupted",
    reviewing: "Payment status is being checked",
    doNotRepay: "Please do not pay again.",
    thankYou: "Thank you for your purchase.",
    failedTitle: "Payment not successful",
    failedText: "The payment was not completed.",
    retry: "Try again",
    otherMethod: "Other method",
    cancel: "Cancel",
    checkStatus: "Check status",
    callManager: "Call manager",
    unavailable: "Not activated yet",
    active: "Active",
    lowStock: "Low stock",
    outOfStock: "Out of stock",
    variant: "Variants",
    promo: "Promo",
    paperReceipt: "Paper receipt",
    emailReceipt: "Email",
    qrReceipt: "QR code",
    noReceipt: "No receipt",
    print: "Print",
    email: "Email",
    receiptNumber: "Receipt number",
    amount: "Amount",
    paymentMethod: "Payment method",
    roleCashier: "Cashier",
    roleManager: "Manager",
    roleOwner: "Owner",
    startSale: "How do I start a sale?",
    removeItem: "How do I remove an item?",
    printReceipt: "How do I print a receipt?",
    declinedHelp: "What if payment is declined?",
    trainingStep1: "Select product",
    trainingStep2: "Check cart",
    trainingStep3: "Pay",
    trainingStep4: "Choose payment method",
    trainingStep5: "New sale",
    skip: "Skip",
    replayLater: "Replay later",
    completed: "Got it",
    quickActions: "Quick actions",
    ownerMetricRevenue: "Revenue today",
    ownerMetricSales: "Sales today",
    ownerMetricPayouts: "Open payouts",
    ownerMetricStock: "Low stock",
    ownerMetricDevices: "Device issues",
    ownerMetricTasks: "Open tasks",
    managerMetricShifts: "Open shifts",
    managerMetricRefunds: "Refunds",
    managerMetricDevice: "Device issues",
    managerMetricStock: "Stock alerts",
    managerMetricRevenue: "Daily revenue",
    actionOpenPos: "Open checkout",
    actionAddProduct: "Add product",
    actionInviteStaff: "Invite staff",
    actionViewReport: "View report",
    actionFindSale: "Find sale",
    actionReviewRefunds: "Review refund",
    actionReviewShift: "Review shift",
    cashDescription: "Complete instantly and calculate change",
    cardDescription: "Hold card or phone to the terminal",
    walletDescription: "Pay by QR code or BidBlitz ID",
    qrDescription: "Customer scans the QR code",
    voucherDescription: "Redeem or apply voucher",
    invoiceDescription: "Pay later after approval",
    tapToPayDescription: "Only with certified provider",
    statusAnnouncement: "Current payment status",
    cartLocked: "The cart is locked while a payment is open.",
    statusRefreshed: "Payment status updated.",
    customerReady: "Please choose a payment method",
    hardwareHint: "Detailed diagnostics belong to /merchant/pos/hardware",
    mockedEmail: "Email receipt will be connected in the next step.",
    qty: "Qty",
    products: "Products",
  },
};

export function getPosCopy(lang = "de") {
  const resolved = lang === "en-US" ? "en" : lang === "sq-XK" ? "sq" : lang === "ar-AE" ? "ar" : lang;
  return COPY[resolved] || COPY.de;
}