import { useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { useLanguage } from '../context/LanguageContext';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { 
  Star, TrendingUp, Users, DollarSign, Gift, Check, 
  Instagram, Youtube, Zap, Award, Target, ArrowRight,
  Sparkles, Crown, Heart, Camera, MessageCircle
} from 'lucide-react';
import { toast } from 'sonner';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

// Translations
const translations = {
  de: {
    badge: "Influencer-Programm",
    heroTitle: "Werden Sie",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Verdienen Sie Geld mit Ihrer Reichweite! Werden Sie Teil unseres Influencer-Programms und erhalten Sie bis zu",
    commission: "30% Provision",
    heroDescEnd: "auf alle Käufe Ihrer Follower.",
    applyNow: "Jetzt bewerben",
    alreadyPartner: "Bereits Partner? Einloggen",
    maxCommission: "Max. Provision",
    activePartners: "Aktive Partner",
    paidOut: "Ausgezahlt",
    activation: "Freischaltung",
    benefitsTitle: "Ihre Vorteile als Partner",
    benefit1Title: "Bis zu 30% Provision",
    benefit1Desc: "Verdienen Sie an jedem Kauf Ihrer Follower",
    benefit2Title: "Exklusive Rabatte",
    benefit2Desc: "Bieten Sie Ihren Followern 5-10% Rabatt",
    benefit3Title: "Gratis Gebote",
    benefit3Desc: "Monatliche Gratis-Gebote zum Testen",
    benefit4Title: "VIP-Status",
    benefit4Desc: "Zugang zu exklusiven VIP-Auktionen",
    benefit5Title: "Eigenes Dashboard",
    benefit5Desc: "Echtzeit-Tracking Ihrer Einnahmen",
    benefit6Title: "Bonus-Programm",
    benefit6Desc: "Extra Boni bei Erreichen von Zielen",
    howItWorks: "So funktioniert's",
    step1Title: "Bewerben",
    step1Desc: "Füllen Sie das Formular aus",
    step2Title: "Freischaltung",
    step2Desc: "Wir prüfen und aktivieren Ihren Account",
    step3Title: "Teilen",
    step3Desc: "Promoten Sie BidBlitz bei Ihren Followern",
    step4Title: "Verdienen",
    step4Desc: "Erhalten Sie Provision für jeden Kauf",
    becomePartner: "Partner werden",
    name: "Name",
    email: "E-Mail",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Follower-Anzahl (gesamt)",
    followersPlaceholder: "z.B. 10.000",
    message: "Nachricht (optional)",
    messagePlaceholder: "Erzählen Sie uns mehr über sich...",
    submit: "Bewerbung absenden",
    submitting: "Wird gesendet...",
    successTitle: "Bewerbung erhalten!",
    successDesc: "Vielen Dank für Ihr Interesse! Wir werden Ihre Bewerbung prüfen und uns innerhalb von 24-48 Stunden bei Ihnen melden.",
    backToHome: "Zur Startseite",
    yourName: "Ihr Name",
    yourEmail: "ihre@email.de",
    username: "@username",
    channel: "Channel",
    applicationSuccess: "Bewerbung erfolgreich gesendet!",
    applicationError: "Fehler beim Senden"
  },
  en: {
    badge: "Influencer Program",
    heroTitle: "Become a",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Earn money with your reach! Join our influencer program and receive up to",
    commission: "30% Commission",
    heroDescEnd: "on all purchases from your followers.",
    applyNow: "Apply Now",
    alreadyPartner: "Already a partner? Login",
    maxCommission: "Max. Commission",
    activePartners: "Active Partners",
    paidOut: "Paid Out",
    activation: "Activation",
    benefitsTitle: "Your Benefits as Partner",
    benefit1Title: "Up to 30% Commission",
    benefit1Desc: "Earn on every purchase from your followers",
    benefit2Title: "Exclusive Discounts",
    benefit2Desc: "Offer your followers 5-10% discount",
    benefit3Title: "Free Bids",
    benefit3Desc: "Monthly free bids for testing",
    benefit4Title: "VIP Status",
    benefit4Desc: "Access to exclusive VIP auctions",
    benefit5Title: "Personal Dashboard",
    benefit5Desc: "Real-time tracking of your earnings",
    benefit6Title: "Bonus Program",
    benefit6Desc: "Extra bonuses when reaching goals",
    howItWorks: "How it Works",
    step1Title: "Apply",
    step1Desc: "Fill out the form",
    step2Title: "Activation",
    step2Desc: "We review and activate your account",
    step3Title: "Share",
    step3Desc: "Promote BidBlitz to your followers",
    step4Title: "Earn",
    step4Desc: "Receive commission for every purchase",
    becomePartner: "Become Partner",
    name: "Name",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Total Followers",
    followersPlaceholder: "e.g. 10,000",
    message: "Message (optional)",
    messagePlaceholder: "Tell us more about yourself...",
    submit: "Submit Application",
    submitting: "Submitting...",
    successTitle: "Application Received!",
    successDesc: "Thank you for your interest! We will review your application and contact you within 24-48 hours.",
    backToHome: "Back to Home",
    yourName: "Your name",
    yourEmail: "your@email.com",
    username: "@username",
    channel: "Channel",
    applicationSuccess: "Application sent successfully!",
    applicationError: "Error submitting"
  },
  tr: {
    badge: "Influencer Programı",
    heroTitle: "Olun",
    heroTitleHighlight: "BidBlitz Ortağı",
    heroDesc: "Erişiminizle para kazanın! Influencer programımıza katılın ve takipçilerinizin tüm alışverişlerinden",
    commission: "%30 Komisyon",
    heroDescEnd: "alın.",
    applyNow: "Şimdi Başvur",
    alreadyPartner: "Zaten ortak mısınız? Giriş yapın",
    maxCommission: "Maks. Komisyon",
    activePartners: "Aktif Ortaklar",
    paidOut: "Ödenen",
    activation: "Aktivasyon",
    benefitsTitle: "Ortak Olarak Avantajlarınız",
    benefit1Title: "%30'e Kadar Komisyon",
    benefit1Desc: "Takipçilerinizin her alışverişinden kazanın",
    benefit2Title: "Özel İndirimler",
    benefit2Desc: "Takipçilerinize %5-10 indirim sunun",
    benefit3Title: "Ücretsiz Teklifler",
    benefit3Desc: "Test için aylık ücretsiz teklifler",
    benefit4Title: "VIP Statüsü",
    benefit4Desc: "Özel VIP müzayedelerine erişim",
    benefit5Title: "Kişisel Panel",
    benefit5Desc: "Kazançlarınızın gerçek zamanlı takibi",
    benefit6Title: "Bonus Programı",
    benefit6Desc: "Hedeflere ulaşınca ekstra bonuslar",
    howItWorks: "Nasıl Çalışır",
    step1Title: "Başvur",
    step1Desc: "Formu doldurun",
    step2Title: "Aktivasyon",
    step2Desc: "Başvurunuzu inceleyip hesabınızı aktif ediyoruz",
    step3Title: "Paylaş",
    step3Desc: "BidBlitz'i takipçilerinize tanıtın",
    step4Title: "Kazan",
    step4Desc: "Her alışverişten komisyon alın",
    becomePartner: "Ortak Ol",
    name: "İsim",
    email: "E-posta",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Toplam Takipçi",
    followersPlaceholder: "örn. 10.000",
    message: "Mesaj (isteğe bağlı)",
    messagePlaceholder: "Kendinizden bahsedin...",
    submit: "Başvuruyu Gönder",
    submitting: "Gönderiliyor...",
    successTitle: "Başvuru Alındı!",
    successDesc: "İlginiz için teşekkürler! Başvurunuzu inceleyip 24-48 saat içinde sizinle iletişime geçeceğiz.",
    backToHome: "Ana Sayfaya Dön",
    yourName: "Adınız",
    yourEmail: "email@adresiniz.com",
    username: "@kullanıcıadı",
    channel: "Kanal",
    applicationSuccess: "Başvuru başarıyla gönderildi!",
    applicationError: "Gönderme hatası"
  },
  fr: {
    badge: "Programme Influenceur",
    heroTitle: "Devenez",
    heroTitleHighlight: "Partenaire BidBlitz",
    heroDesc: "Gagnez de l'argent avec votre portée! Rejoignez notre programme influenceur et recevez jusqu'à",
    commission: "30% de Commission",
    heroDescEnd: "sur tous les achats de vos abonnés.",
    applyNow: "Postuler Maintenant",
    alreadyPartner: "Déjà partenaire? Connexion",
    maxCommission: "Commission Max.",
    activePartners: "Partenaires Actifs",
    paidOut: "Payé",
    activation: "Activation",
    benefitsTitle: "Vos Avantages en tant que Partenaire",
    benefit1Title: "Jusqu'à 30% de Commission",
    benefit1Desc: "Gagnez sur chaque achat de vos abonnés",
    benefit2Title: "Réductions Exclusives",
    benefit2Desc: "Offrez 5-10% de réduction à vos abonnés",
    benefit3Title: "Enchères Gratuites",
    benefit3Desc: "Enchères gratuites mensuelles pour tester",
    benefit4Title: "Statut VIP",
    benefit4Desc: "Accès aux enchères VIP exclusives",
    benefit5Title: "Tableau de Bord Personnel",
    benefit5Desc: "Suivi en temps réel de vos gains",
    benefit6Title: "Programme de Bonus",
    benefit6Desc: "Bonus supplémentaires en atteignant les objectifs",
    howItWorks: "Comment ça Marche",
    step1Title: "Postuler",
    step1Desc: "Remplissez le formulaire",
    step2Title: "Activation",
    step2Desc: "Nous examinons et activons votre compte",
    step3Title: "Partager",
    step3Desc: "Promouvez BidBlitz auprès de vos abonnés",
    step4Title: "Gagner",
    step4Desc: "Recevez une commission pour chaque achat",
    becomePartner: "Devenir Partenaire",
    name: "Nom",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Nombre Total d'Abonnés",
    followersPlaceholder: "ex. 10 000",
    message: "Message (optionnel)",
    messagePlaceholder: "Parlez-nous de vous...",
    submit: "Envoyer la Candidature",
    submitting: "Envoi en cours...",
    successTitle: "Candidature Reçue!",
    successDesc: "Merci pour votre intérêt! Nous examinerons votre candidature et vous contacterons dans les 24-48 heures.",
    backToHome: "Retour à l'Accueil",
    yourName: "Votre nom",
    yourEmail: "votre@email.com",
    username: "@utilisateur",
    channel: "Chaîne",
    applicationSuccess: "Candidature envoyée avec succès!",
    applicationError: "Erreur lors de l'envoi"
  },
  sq: {
    badge: "Programi i Influencerëve",
    heroTitle: "Bëhuni",
    heroTitleHighlight: "Partner i BidBlitz",
    heroDesc: "Fitoni para me shtrirjen tuaj! Bashkohuni me programin tonë të influencerëve dhe merrni deri në",
    commission: "30% Komision",
    heroDescEnd: "për të gjitha blerjet e ndjekësve tuaj.",
    applyNow: "Apliko Tani",
    alreadyPartner: "Tashmë partner? Hyni",
    maxCommission: "Komisioni Maks.",
    activePartners: "Partnerë Aktivë",
    paidOut: "E Paguar",
    activation: "Aktivizimi",
    benefitsTitle: "Përfitimet Tuaja si Partner",
    benefit1Title: "Deri në 30% Komision",
    benefit1Desc: "Fitoni nga çdo blerje e ndjekësve tuaj",
    benefit2Title: "Zbritje Ekskluzive",
    benefit2Desc: "Ofroni ndjekësve tuaj 5-10% zbritje",
    benefit3Title: "Oferta Falas",
    benefit3Desc: "Oferta mujore falas për testim",
    benefit4Title: "Statusi VIP",
    benefit4Desc: "Qasje në ankandet ekskluzive VIP",
    benefit5Title: "Paneli Personal",
    benefit5Desc: "Ndjekje në kohë reale e fitimeve",
    benefit6Title: "Programi i Bonusit",
    benefit6Desc: "Bonuse shtesë kur arrini objektivat",
    howItWorks: "Si Funksionon",
    step1Title: "Apliko",
    step1Desc: "Plotësoni formularin",
    step2Title: "Aktivizimi",
    step2Desc: "Ne shqyrtojmë dhe aktivizojmë llogarinë tuaj",
    step3Title: "Ndaj",
    step3Desc: "Promovoni BidBlitz tek ndjekësit tuaj",
    step4Title: "Fito",
    step4Desc: "Merrni komision për çdo blerje",
    becomePartner: "Bëhu Partner",
    name: "Emri",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Numri Total i Ndjekësve",
    followersPlaceholder: "p.sh. 10,000",
    message: "Mesazh (opsional)",
    messagePlaceholder: "Na tregoni më shumë për veten...",
    submit: "Dërgo Aplikimin",
    submitting: "Duke dërguar...",
    successTitle: "Aplikimi u Mor!",
    successDesc: "Faleminderit për interesin tuaj! Ne do të shqyrtojmë aplikimin tuaj dhe do t'ju kontaktojmë brenda 24-48 orëve.",
    backToHome: "Kthehu në Ballina",
    yourName: "Emri juaj",
    yourEmail: "email@juaj.com",
    username: "@përdoruesi",
    channel: "Kanali",
    applicationSuccess: "Aplikimi u dërgua me sukses!",
    applicationError: "Gabim gjatë dërgimit"
  },
  xk: {
    badge: "Programi i Influencerëve",
    heroTitle: "Bëhuni",
    heroTitleHighlight: "Partner i BidBlitz",
    heroDesc: "Fitoni para me shtrirjen tuaj! Bashkohuni me programin tonë të influencerëve dhe merrni deri në",
    commission: "30% Komision",
    heroDescEnd: "për të gjitha blerjet e ndjekësve tuaj.",
    applyNow: "Apliko Tani",
    alreadyPartner: "Tashmë partner? Kyçu",
    maxCommission: "Komisioni Maks.",
    activePartners: "Partnerë Aktivë",
    paidOut: "E Paguar",
    activation: "Aktivizimi",
    benefitsTitle: "Përfitimet Tuaja si Partner",
    benefit1Title: "Deri në 30% Komision",
    benefit1Desc: "Fitoni nga çdo blerje e ndjekësve tuaj",
    benefit2Title: "Zbritje Ekskluzive",
    benefit2Desc: "Ofroni ndjekësve tuaj 5-10% zbritje",
    benefit3Title: "Oferta Falas",
    benefit3Desc: "Oferta mujore falas për testim",
    benefit4Title: "Statusi VIP",
    benefit4Desc: "Qasje në ankandet ekskluzive VIP",
    benefit5Title: "Paneli Personal",
    benefit5Desc: "Ndjekje në kohë reale e fitimeve",
    benefit6Title: "Programi i Bonusit",
    benefit6Desc: "Bonuse shtesë kur arrini objektivat",
    howItWorks: "Si Funksionon",
    step1Title: "Apliko",
    step1Desc: "Plotësoni formularin",
    step2Title: "Aktivizimi",
    step2Desc: "Ne shqyrtojmë dhe aktivizojmë llogarinë tuaj",
    step3Title: "Ndaj",
    step3Desc: "Promovoni BidBlitz tek ndjekësit tuaj",
    step4Title: "Fito",
    step4Desc: "Merrni komision për çdo blerje",
    becomePartner: "Bëhu Partner",
    name: "Emri",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Numri Total i Ndjekësve",
    followersPlaceholder: "p.sh. 10,000",
    message: "Mesazh (opsional)",
    messagePlaceholder: "Na tregoni më shumë për veten...",
    submit: "Dërgo Aplikimin",
    submitting: "Duke dërguar...",
    successTitle: "Aplikimi u Mor!",
    successDesc: "Faleminderit për interesin tuaj! Ne do të shqyrtojmë aplikimin tuaj dhe do t'ju kontaktojmë brenda 24-48 orëve.",
    backToHome: "Kthehu në Ballina",
    yourName: "Emri juaj",
    yourEmail: "email@juaj.com",
    username: "@përdoruesi",
    channel: "Kanali",
    applicationSuccess: "Aplikimi u dërgua me sukses!",
    applicationError: "Gabim gjatë dërgimit"
  },
  xk: {
    badge: "Programi i Influencerëve",
    heroTitle: "Bëhuni",
    heroTitleHighlight: "Partner i BidBlitz",
    heroDesc: "Fitoni para me shtrirjen tuaj! Bashkohuni me programin tonë të influencerëve dhe merrni deri në",
    commission: "30% Komision",
    heroDescEnd: "për të gjitha blerjet e ndjekësve tuaj.",
    applyNow: "Apliko Tani",
    alreadyPartner: "Tashmë partner? Kyçu",
    maxCommission: "Komisioni Maks.",
    activePartners: "Partnerë Aktivë",
    paidOut: "E Paguar",
    activation: "Aktivizimi",
    benefitsTitle: "Përfitimet Tuaja si Partner",
    benefit1Title: "Deri në 30% Komision",
    benefit1Desc: "Fitoni nga çdo blerje e ndjekësve tuaj",
    benefit2Title: "Zbritje Ekskluzive",
    benefit2Desc: "Ofroni ndjekësve tuaj 5-10% zbritje",
    benefit3Title: "Oferta Falas",
    benefit3Desc: "Oferta mujore falas për testim",
    benefit4Title: "Statusi VIP",
    benefit4Desc: "Qasje në ankandet ekskluzive VIP",
    benefit5Title: "Paneli Personal",
    benefit5Desc: "Ndjekje në kohë reale e fitimeve",
    benefit6Title: "Programi i Bonusit",
    benefit6Desc: "Bonuse shtesë kur arrini objektivat",
    howItWorks: "Si Funksionon",
    step1Title: "Apliko",
    step1Desc: "Plotësoni formularin",
    step2Title: "Aktivizimi",
    step2Desc: "Ne shqyrtojmë dhe aktivizojmë llogarinë tuaj",
    step3Title: "Ndaj",
    step3Desc: "Promovoni BidBlitz tek ndjekësit tuaj",
    step4Title: "Fito",
    step4Desc: "Merrni komision për çdo blerje",
    becomePartner: "Bëhu Partner",
    name: "Emri",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Numri Total i Ndjekësve",
    followersPlaceholder: "p.sh. 10,000",
    message: "Mesazh (opsional)",
    messagePlaceholder: "Na tregoni më shumë për veten...",
    submit: "Dërgo Aplikimin",
    submitting: "Duke dërguar...",
    successTitle: "Aplikimi u Mor!",
    successDesc: "Faleminderit për interesin tuaj! Ne do të shqyrtojmë aplikimin tuaj dhe do t'ju kontaktojmë brenda 24-48 orëve.",
    backToHome: "Kthehu në Ballina",
    yourName: "Emri juaj",
    yourEmail: "email@juaj.com",
    username: "@përdoruesi",
    channel: "Kanali",
    applicationSuccess: "Aplikimi u dërgua me sukses!",
    applicationError: "Gabim gjatë dërgimit"
  },
  us: {
    badge: "Influencer Program",
    heroTitle: "Become a",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Earn money with your reach! Join our influencer program and receive up to",
    commission: "30% Commission",
    heroDescEnd: "on all purchases from your followers.",
    applyNow: "Apply Now",
    alreadyPartner: "Already a partner? Login",
    maxCommission: "Max. Commission",
    activePartners: "Active Partners",
    paidOut: "Paid Out",
    activation: "Activation",
    benefitsTitle: "Your Benefits as Partner",
    benefit1Title: "Up to 30% Commission",
    benefit1Desc: "Earn on every purchase from your followers",
    benefit2Title: "Exclusive Discounts",
    benefit2Desc: "Offer your followers 5-10% discount",
    benefit3Title: "Free Bids",
    benefit3Desc: "Monthly free bids for testing",
    benefit4Title: "VIP Status",
    benefit4Desc: "Access to exclusive VIP auctions",
    benefit5Title: "Personal Dashboard",
    benefit5Desc: "Real-time tracking of your earnings",
    benefit6Title: "Bonus Program",
    benefit6Desc: "Extra bonuses when reaching goals",
    howItWorks: "How it Works",
    step1Title: "Apply",
    step1Desc: "Fill out the form",
    step2Title: "Activation",
    step2Desc: "We review and activate your account",
    step3Title: "Share",
    step3Desc: "Promote BidBlitz to your followers",
    step4Title: "Earn",
    step4Desc: "Receive commission for every purchase",
    becomePartner: "Become Partner",
    name: "Name",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Total Followers",
    followersPlaceholder: "e.g. 10,000",
    message: "Message (optional)",
    messagePlaceholder: "Tell us more about yourself...",
    submit: "Submit Application",
    submitting: "Submitting...",
    successTitle: "Application Received!",
    successDesc: "Thank you for your interest! We will review your application and contact you within 24-48 hours.",
    backToHome: "Back to Home",
    yourName: "Your name",
    yourEmail: "your@email.com",
    username: "@username",
    channel: "Channel",
    applicationSuccess: "Application sent successfully!",
    applicationError: "Error submitting"
  },
  es: {
    badge: "Programa de Influencers",
    heroTitle: "Conviértete en",
    heroTitleHighlight: "Partner de BidBlitz",
    heroDesc: "¡Gana dinero con tu alcance! Únete a nuestro programa de influencers y recibe hasta",
    commission: "30% Comisión",
    heroDescEnd: "en todas las compras de tus seguidores.",
    applyNow: "Aplicar Ahora",
    alreadyPartner: "¿Ya eres partner? Iniciar sesión",
    maxCommission: "Comisión Máx.",
    activePartners: "Partners Activos",
    paidOut: "Pagado",
    activation: "Activación",
    benefitsTitle: "Tus Beneficios como Partner",
    benefit1Title: "Hasta 30% Comisión",
    benefit1Desc: "Gana en cada compra de tus seguidores",
    benefit2Title: "Descuentos Exclusivos",
    benefit2Desc: "Ofrece a tus seguidores 5-10% descuento",
    benefit3Title: "Ofertas Gratis",
    benefit3Desc: "Ofertas mensuales gratis para probar",
    benefit4Title: "Estado VIP",
    benefit4Desc: "Acceso a subastas VIP exclusivas",
    benefit5Title: "Panel Personal",
    benefit5Desc: "Seguimiento en tiempo real de tus ganancias",
    benefit6Title: "Programa de Bonus",
    benefit6Desc: "Bonos extra al alcanzar objetivos",
    howItWorks: "Cómo Funciona",
    step1Title: "Aplica",
    step1Desc: "Rellena el formulario",
    step2Title: "Activación",
    step2Desc: "Revisamos y activamos tu cuenta",
    step3Title: "Comparte",
    step3Desc: "Promociona BidBlitz a tus seguidores",
    step4Title: "Gana",
    step4Desc: "Recibe comisión por cada compra",
    becomePartner: "Ser Partner",
    name: "Nombre",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Total Seguidores",
    followersPlaceholder: "ej. 10,000",
    message: "Mensaje (opcional)",
    messagePlaceholder: "Cuéntanos más sobre ti...",
    submit: "Enviar Solicitud",
    submitting: "Enviando...",
    successTitle: "¡Solicitud Recibida!",
    successDesc: "¡Gracias por tu interés! Revisaremos tu solicitud y te contactaremos en 24-48 horas.",
    backToHome: "Volver al Inicio",
    yourName: "Tu nombre",
    yourEmail: "tu@email.com",
    username: "@usuario",
    channel: "Canal",
    applicationSuccess: "¡Solicitud enviada con éxito!",
    applicationError: "Error al enviar"
  },
  it: {
    badge: "Programma Influencer",
    heroTitle: "Diventa",
    heroTitleHighlight: "Partner di BidBlitz",
    heroDesc: "Guadagna con la tua portata! Unisciti al nostro programma influencer e ricevi fino a",
    commission: "30% Commissione",
    heroDescEnd: "su tutti gli acquisti dei tuoi follower.",
    applyNow: "Candidati Ora",
    alreadyPartner: "Già partner? Accedi",
    maxCommission: "Commissione Max.",
    activePartners: "Partner Attivi",
    paidOut: "Pagato",
    activation: "Attivazione",
    benefitsTitle: "I Tuoi Vantaggi come Partner",
    benefit1Title: "Fino al 30% Commissione",
    benefit1Desc: "Guadagna su ogni acquisto dei tuoi follower",
    benefit2Title: "Sconti Esclusivi",
    benefit2Desc: "Offri ai tuoi follower 5-10% di sconto",
    benefit3Title: "Offerte Gratuite",
    benefit3Desc: "Offerte mensili gratuite per testare",
    benefit4Title: "Status VIP",
    benefit4Desc: "Accesso alle aste VIP esclusive",
    benefit5Title: "Dashboard Personale",
    benefit5Desc: "Monitoraggio in tempo reale dei guadagni",
    benefit6Title: "Programma Bonus",
    benefit6Desc: "Bonus extra al raggiungimento degli obiettivi",
    howItWorks: "Come Funziona",
    step1Title: "Candidati",
    step1Desc: "Compila il modulo",
    step2Title: "Attivazione",
    step2Desc: "Esaminiamo e attiviamo il tuo account",
    step3Title: "Condividi",
    step3Desc: "Promuovi BidBlitz ai tuoi follower",
    step4Title: "Guadagna",
    step4Desc: "Ricevi commissione per ogni acquisto",
    becomePartner: "Diventa Partner",
    name: "Nome",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Totale Follower",
    followersPlaceholder: "es. 10.000",
    message: "Messaggio (opzionale)",
    messagePlaceholder: "Raccontaci di più su di te...",
    submit: "Invia Candidatura",
    submitting: "Invio in corso...",
    successTitle: "Candidatura Ricevuta!",
    successDesc: "Grazie per il tuo interesse! Esamineremo la tua candidatura e ti contatteremo entro 24-48 ore.",
    backToHome: "Torna alla Home",
    yourName: "Il tuo nome",
    yourEmail: "tua@email.com",
    username: "@utente",
    channel: "Canale",
    applicationSuccess: "Candidatura inviata con successo!",
    applicationError: "Errore durante l'invio"
  },
  pt: {
    badge: "Programa de Influenciadores",
    heroTitle: "Torne-se",
    heroTitleHighlight: "Parceiro BidBlitz",
    heroDesc: "Ganhe dinheiro com seu alcance! Junte-se ao nosso programa de influenciadores e receba até",
    commission: "30% Comissão",
    heroDescEnd: "em todas as compras dos seus seguidores.",
    applyNow: "Candidatar Agora",
    alreadyPartner: "Já é parceiro? Entrar",
    maxCommission: "Comissão Máx.",
    activePartners: "Parceiros Ativos",
    paidOut: "Pago",
    activation: "Ativação",
    benefitsTitle: "Seus Benefícios como Parceiro",
    benefit1Title: "Até 30% Comissão",
    benefit1Desc: "Ganhe em cada compra dos seus seguidores",
    benefit2Title: "Descontos Exclusivos",
    benefit2Desc: "Ofereça aos seguidores 5-10% desconto",
    benefit3Title: "Ofertas Grátis",
    benefit3Desc: "Ofertas mensais grátis para testar",
    benefit4Title: "Status VIP",
    benefit4Desc: "Acesso a leilões VIP exclusivos",
    benefit5Title: "Painel Pessoal",
    benefit5Desc: "Acompanhamento em tempo real dos ganhos",
    benefit6Title: "Programa de Bônus",
    benefit6Desc: "Bônus extra ao atingir metas",
    howItWorks: "Como Funciona",
    step1Title: "Candidate-se",
    step1Desc: "Preencha o formulário",
    step2Title: "Ativação",
    step2Desc: "Analisamos e ativamos sua conta",
    step3Title: "Compartilhe",
    step3Desc: "Promova BidBlitz aos seus seguidores",
    step4Title: "Ganhe",
    step4Desc: "Receba comissão por cada compra",
    becomePartner: "Ser Parceiro",
    name: "Nome",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Total Seguidores",
    followersPlaceholder: "ex. 10.000",
    message: "Mensagem (opcional)",
    messagePlaceholder: "Conte-nos mais sobre você...",
    submit: "Enviar Candidatura",
    submitting: "Enviando...",
    successTitle: "Candidatura Recebida!",
    successDesc: "Obrigado pelo seu interesse! Analisaremos sua candidatura e entraremos em contato em 24-48 horas.",
    backToHome: "Voltar ao Início",
    yourName: "Seu nome",
    yourEmail: "seu@email.com",
    username: "@usuario",
    channel: "Canal",
    applicationSuccess: "Candidatura enviada com sucesso!",
    applicationError: "Erro ao enviar"
  },
  nl: {
    badge: "Influencer Programma",
    heroTitle: "Word",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Verdien geld met je bereik! Word lid van ons influencer programma en ontvang tot",
    commission: "30% Commissie",
    heroDescEnd: "op alle aankopen van je volgers.",
    applyNow: "Nu Aanmelden",
    alreadyPartner: "Al partner? Inloggen",
    maxCommission: "Max. Commissie",
    activePartners: "Actieve Partners",
    paidOut: "Uitbetaald",
    activation: "Activering",
    benefitsTitle: "Jouw Voordelen als Partner",
    benefit1Title: "Tot 30% Commissie",
    benefit1Desc: "Verdien bij elke aankoop van je volgers",
    benefit2Title: "Exclusieve Kortingen",
    benefit2Desc: "Bied je volgers 5-10% korting",
    benefit3Title: "Gratis Biedingen",
    benefit3Desc: "Maandelijkse gratis biedingen om te testen",
    benefit4Title: "VIP Status",
    benefit4Desc: "Toegang tot exclusieve VIP veilingen",
    benefit5Title: "Persoonlijk Dashboard",
    benefit5Desc: "Realtime tracking van je verdiensten",
    benefit6Title: "Bonus Programma",
    benefit6Desc: "Extra bonussen bij het behalen van doelen",
    howItWorks: "Hoe het Werkt",
    step1Title: "Aanmelden",
    step1Desc: "Vul het formulier in",
    step2Title: "Activering",
    step2Desc: "We beoordelen en activeren je account",
    step3Title: "Delen",
    step3Desc: "Promoot BidBlitz bij je volgers",
    step4Title: "Verdienen",
    step4Desc: "Ontvang commissie voor elke aankoop",
    becomePartner: "Word Partner",
    name: "Naam",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Totaal Volgers",
    followersPlaceholder: "bijv. 10.000",
    message: "Bericht (optioneel)",
    messagePlaceholder: "Vertel ons meer over jezelf...",
    submit: "Aanmelding Verzenden",
    submitting: "Verzenden...",
    successTitle: "Aanmelding Ontvangen!",
    successDesc: "Bedankt voor je interesse! We beoordelen je aanmelding en nemen binnen 24-48 uur contact op.",
    backToHome: "Terug naar Home",
    yourName: "Je naam",
    yourEmail: "jouw@email.nl",
    username: "@gebruiker",
    channel: "Kanaal",
    applicationSuccess: "Aanmelding succesvol verzonden!",
    applicationError: "Fout bij verzenden"
  },
  pl: {
    badge: "Program Influencerów",
    heroTitle: "Zostań",
    heroTitleHighlight: "Partnerem BidBlitz",
    heroDesc: "Zarabiaj na swoim zasięgu! Dołącz do programu influencerów i otrzymuj do",
    commission: "30% Prowizji",
    heroDescEnd: "od wszystkich zakupów twoich obserwujących.",
    applyNow: "Aplikuj Teraz",
    alreadyPartner: "Już partner? Zaloguj się",
    maxCommission: "Maks. Prowizja",
    activePartners: "Aktywni Partnerzy",
    paidOut: "Wypłacono",
    activation: "Aktywacja",
    benefitsTitle: "Twoje Korzyści jako Partner",
    benefit1Title: "Do 30% Prowizji",
    benefit1Desc: "Zarabiaj na każdym zakupie obserwujących",
    benefit2Title: "Ekskluzywne Zniżki",
    benefit2Desc: "Oferuj obserwującym 5-10% zniżki",
    benefit3Title: "Darmowe Oferty",
    benefit3Desc: "Miesięczne darmowe oferty do testowania",
    benefit4Title: "Status VIP",
    benefit4Desc: "Dostęp do ekskluzywnych aukcji VIP",
    benefit5Title: "Panel Osobisty",
    benefit5Desc: "Śledzenie zarobków w czasie rzeczywistym",
    benefit6Title: "Program Bonusowy",
    benefit6Desc: "Dodatkowe bonusy za osiągnięcie celów",
    howItWorks: "Jak to Działa",
    step1Title: "Aplikuj",
    step1Desc: "Wypełnij formularz",
    step2Title: "Aktywacja",
    step2Desc: "Sprawdzamy i aktywujemy twoje konto",
    step3Title: "Udostępnij",
    step3Desc: "Promuj BidBlitz wśród obserwujących",
    step4Title: "Zarabiaj",
    step4Desc: "Otrzymuj prowizję za każdy zakup",
    becomePartner: "Zostań Partnerem",
    name: "Imię",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Liczba Obserwujących",
    followersPlaceholder: "np. 10 000",
    message: "Wiadomość (opcjonalnie)",
    messagePlaceholder: "Opowiedz nam więcej o sobie...",
    submit: "Wyślij Aplikację",
    submitting: "Wysyłanie...",
    successTitle: "Aplikacja Otrzymana!",
    successDesc: "Dziękujemy za zainteresowanie! Sprawdzimy aplikację i skontaktujemy się w ciągu 24-48 godzin.",
    backToHome: "Powrót do Strony Głównej",
    yourName: "Twoje imię",
    yourEmail: "twoj@email.pl",
    username: "@uzytkownik",
    channel: "Kanał",
    applicationSuccess: "Aplikacja wysłana pomyślnie!",
    applicationError: "Błąd podczas wysyłania"
  },
  ru: {
    badge: "Программа Инфлюенсеров",
    heroTitle: "Станьте",
    heroTitleHighlight: "Партнером BidBlitz",
    heroDesc: "Зарабатывайте на своем охвате! Присоединяйтесь к программе инфлюенсеров и получайте до",
    commission: "30% Комиссии",
    heroDescEnd: "со всех покупок ваших подписчиков.",
    applyNow: "Подать Заявку",
    alreadyPartner: "Уже партнер? Войти",
    maxCommission: "Макс. Комиссия",
    activePartners: "Активных Партнеров",
    paidOut: "Выплачено",
    activation: "Активация",
    benefitsTitle: "Ваши Преимущества как Партнера",
    benefit1Title: "До 30% Комиссии",
    benefit1Desc: "Зарабатывайте с каждой покупки подписчиков",
    benefit2Title: "Эксклюзивные Скидки",
    benefit2Desc: "Предлагайте подписчикам 5-10% скидку",
    benefit3Title: "Бесплатные Ставки",
    benefit3Desc: "Ежемесячные бесплатные ставки для тестирования",
    benefit4Title: "VIP Статус",
    benefit4Desc: "Доступ к эксклюзивным VIP аукционам",
    benefit5Title: "Личный Кабинет",
    benefit5Desc: "Отслеживание заработка в реальном времени",
    benefit6Title: "Бонусная Программа",
    benefit6Desc: "Дополнительные бонусы при достижении целей",
    howItWorks: "Как это Работает",
    step1Title: "Подайте заявку",
    step1Desc: "Заполните форму",
    step2Title: "Активация",
    step2Desc: "Мы проверим и активируем ваш аккаунт",
    step3Title: "Делитесь",
    step3Desc: "Рекламируйте BidBlitz подписчикам",
    step4Title: "Зарабатывайте",
    step4Desc: "Получайте комиссию за каждую покупку",
    becomePartner: "Стать Партнером",
    name: "Имя",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Всего Подписчиков",
    followersPlaceholder: "напр. 10 000",
    message: "Сообщение (необязательно)",
    messagePlaceholder: "Расскажите нам больше о себе...",
    submit: "Отправить Заявку",
    submitting: "Отправка...",
    successTitle: "Заявка Получена!",
    successDesc: "Спасибо за интерес! Мы рассмотрим заявку и свяжемся с вами в течение 24-48 часов.",
    backToHome: "На Главную",
    yourName: "Ваше имя",
    yourEmail: "ваш@email.ru",
    username: "@пользователь",
    channel: "Канал",
    applicationSuccess: "Заявка успешно отправлена!",
    applicationError: "Ошибка при отправке"
  },
  ar: {
    badge: "برنامج المؤثرين",
    heroTitle: "كن",
    heroTitleHighlight: "شريك BidBlitz",
    heroDesc: "اكسب المال من خلال وصولك! انضم إلى برنامج المؤثرين واحصل على ما يصل إلى",
    commission: "30% عمولة",
    heroDescEnd: "على جميع مشتريات متابعيك.",
    applyNow: "قدم الآن",
    alreadyPartner: "شريك بالفعل؟ تسجيل الدخول",
    maxCommission: "أقصى عمولة",
    activePartners: "شركاء نشطون",
    paidOut: "المدفوع",
    activation: "التفعيل",
    benefitsTitle: "مزاياك كشريك",
    benefit1Title: "حتى 30% عمولة",
    benefit1Desc: "اكسب من كل عملية شراء لمتابعيك",
    benefit2Title: "خصومات حصرية",
    benefit2Desc: "قدم لمتابعيك خصم 5-10%",
    benefit3Title: "عروض مجانية",
    benefit3Desc: "عروض شهرية مجانية للاختبار",
    benefit4Title: "حالة VIP",
    benefit4Desc: "الوصول إلى مزادات VIP الحصرية",
    benefit5Title: "لوحة تحكم شخصية",
    benefit5Desc: "تتبع أرباحك في الوقت الفعلي",
    benefit6Title: "برنامج المكافآت",
    benefit6Desc: "مكافآت إضافية عند تحقيق الأهداف",
    howItWorks: "كيف يعمل",
    step1Title: "قدم",
    step1Desc: "املأ النموذج",
    step2Title: "التفعيل",
    step2Desc: "نراجع ونفعل حسابك",
    step3Title: "شارك",
    step3Desc: "روج لـ BidBlitz لمتابعيك",
    step4Title: "اكسب",
    step4Desc: "احصل على عمولة لكل عملية شراء",
    becomePartner: "كن شريكاً",
    name: "الاسم",
    email: "البريد الإلكتروني",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "إجمالي المتابعين",
    followersPlaceholder: "مثال 10,000",
    message: "رسالة (اختياري)",
    messagePlaceholder: "أخبرنا المزيد عن نفسك...",
    submit: "إرسال الطلب",
    submitting: "جاري الإرسال...",
    successTitle: "تم استلام الطلب!",
    successDesc: "شكراً لاهتمامك! سنراجع طلبك ونتواصل معك خلال 24-48 ساعة.",
    backToHome: "العودة للرئيسية",
    yourName: "اسمك",
    yourEmail: "بريدك@email.com",
    username: "@المستخدم",
    channel: "القناة",
    applicationSuccess: "تم إرسال الطلب بنجاح!",
    applicationError: "خطأ في الإرسال"
  },
  ae: {
    badge: "برنامج المؤثرين",
    heroTitle: "كن",
    heroTitleHighlight: "شريك BidBlitz",
    heroDesc: "اكسب المال من خلال وصولك! انضم إلى برنامج المؤثرين واحصل على ما يصل إلى",
    commission: "30% عمولة",
    heroDescEnd: "على جميع مشتريات متابعيك.",
    applyNow: "قدم الآن",
    alreadyPartner: "شريك بالفعل؟ تسجيل الدخول",
    maxCommission: "أقصى عمولة",
    activePartners: "شركاء نشطون",
    paidOut: "المدفوع",
    activation: "التفعيل",
    benefitsTitle: "مزاياك كشريك",
    benefit1Title: "حتى 30% عمولة",
    benefit1Desc: "اكسب من كل عملية شراء لمتابعيك",
    benefit2Title: "خصومات حصرية",
    benefit2Desc: "قدم لمتابعيك خصم 5-10%",
    benefit3Title: "عروض مجانية",
    benefit3Desc: "عروض شهرية مجانية للاختبار",
    benefit4Title: "حالة VIP",
    benefit4Desc: "الوصول إلى مزادات VIP الحصرية",
    benefit5Title: "لوحة تحكم شخصية",
    benefit5Desc: "تتبع أرباحك في الوقت الفعلي",
    benefit6Title: "برنامج المكافآت",
    benefit6Desc: "مكافآت إضافية عند تحقيق الأهداف",
    howItWorks: "كيف يعمل",
    step1Title: "قدم",
    step1Desc: "املأ النموذج",
    step2Title: "التفعيل",
    step2Desc: "نراجع ونفعل حسابك",
    step3Title: "شارك",
    step3Desc: "روج لـ BidBlitz لمتابعيك",
    step4Title: "اكسب",
    step4Desc: "احصل على عمولة لكل عملية شراء",
    becomePartner: "كن شريكاً",
    name: "الاسم",
    email: "البريد الإلكتروني",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "إجمالي المتابعين",
    followersPlaceholder: "مثال 10,000",
    message: "رسالة (اختياري)",
    messagePlaceholder: "أخبرنا المزيد عن نفسك...",
    submit: "إرسال الطلب",
    submitting: "جاري الإرسال...",
    successTitle: "تم استلام الطلب!",
    successDesc: "شكراً لاهتمامك! سنراجع طلبك ونتواصل معك خلال 24-48 ساعة.",
    backToHome: "العودة للرئيسية",
    yourName: "اسمك",
    yourEmail: "بريدك@email.com",
    username: "@المستخدم",
    channel: "القناة",
    applicationSuccess: "تم إرسال الطلب بنجاح!",
    applicationError: "خطأ في الإرسال"
  },
  zh: {
    badge: "网红计划",
    heroTitle: "成为",
    heroTitleHighlight: "BidBlitz合作伙伴",
    heroDesc: "通过您的影响力赚钱！加入我们的网红计划，获得高达",
    commission: "30%佣金",
    heroDescEnd: "来自您粉丝的所有购买。",
    applyNow: "立即申请",
    alreadyPartner: "已是合作伙伴？登录",
    maxCommission: "最高佣金",
    activePartners: "活跃合作伙伴",
    paidOut: "已支付",
    activation: "激活",
    benefitsTitle: "您作为合作伙伴的福利",
    benefit1Title: "高达30%佣金",
    benefit1Desc: "从粉丝的每次购买中赚取",
    benefit2Title: "专属折扣",
    benefit2Desc: "为粉丝提供5-10%折扣",
    benefit3Title: "免费出价",
    benefit3Desc: "每月免费出价用于测试",
    benefit4Title: "VIP身份",
    benefit4Desc: "访问专属VIP拍卖",
    benefit5Title: "个人仪表板",
    benefit5Desc: "实时跟踪您的收入",
    benefit6Title: "奖金计划",
    benefit6Desc: "达到目标时获得额外奖金",
    howItWorks: "如何运作",
    step1Title: "申请",
    step1Desc: "填写表格",
    step2Title: "激活",
    step2Desc: "我们审核并激活您的账户",
    step3Title: "分享",
    step3Desc: "向粉丝推广BidBlitz",
    step4Title: "赚取",
    step4Desc: "每次购买获得佣金",
    becomePartner: "成为合作伙伴",
    name: "姓名",
    email: "邮箱",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "粉丝总数",
    followersPlaceholder: "例如 10,000",
    message: "留言（可选）",
    messagePlaceholder: "告诉我们更多关于您的信息...",
    submit: "提交申请",
    submitting: "提交中...",
    successTitle: "申请已收到！",
    successDesc: "感谢您的关注！我们将审核您的申请并在24-48小时内与您联系。",
    backToHome: "返回首页",
    yourName: "您的姓名",
    yourEmail: "您的邮箱",
    username: "@用户名",
    channel: "频道",
    applicationSuccess: "申请提交成功！",
    applicationError: "提交错误"
  },
  ja: {
    badge: "インフルエンサープログラム",
    heroTitle: "なる",
    heroTitleHighlight: "BidBlitzパートナー",
    heroDesc: "あなたのリーチで収益を得ましょう！インフルエンサープログラムに参加して、最大",
    commission: "30%コミッション",
    heroDescEnd: "フォロワーのすべての購入から。",
    applyNow: "今すぐ申請",
    alreadyPartner: "すでにパートナー？ログイン",
    maxCommission: "最大コミッション",
    activePartners: "アクティブパートナー",
    paidOut: "支払済み",
    activation: "アクティベーション",
    benefitsTitle: "パートナーとしての特典",
    benefit1Title: "最大30%コミッション",
    benefit1Desc: "フォロワーの購入ごとに収益を得る",
    benefit2Title: "限定割引",
    benefit2Desc: "フォロワーに5-10%割引を提供",
    benefit3Title: "無料入札",
    benefit3Desc: "テスト用の月間無料入札",
    benefit4Title: "VIPステータス",
    benefit4Desc: "限定VIPオークションへのアクセス",
    benefit5Title: "個人ダッシュボード",
    benefit5Desc: "収益のリアルタイム追跡",
    benefit6Title: "ボーナスプログラム",
    benefit6Desc: "目標達成時に追加ボーナス",
    howItWorks: "仕組み",
    step1Title: "申請",
    step1Desc: "フォームに記入",
    step2Title: "アクティベーション",
    step2Desc: "審査後アカウントを有効化",
    step3Title: "共有",
    step3Desc: "フォロワーにBidBlitzを宣伝",
    step4Title: "収益",
    step4Desc: "購入ごとにコミッションを受け取る",
    becomePartner: "パートナーになる",
    name: "名前",
    email: "メール",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "フォロワー総数",
    followersPlaceholder: "例: 10,000",
    message: "メッセージ（任意）",
    messagePlaceholder: "自己紹介をお願いします...",
    submit: "申請を送信",
    submitting: "送信中...",
    successTitle: "申請を受け付けました！",
    successDesc: "ご興味ありがとうございます！申請を確認し、24-48時間以内にご連絡いたします。",
    backToHome: "ホームに戻る",
    yourName: "お名前",
    yourEmail: "メールアドレス",
    username: "@ユーザー名",
    channel: "チャンネル",
    applicationSuccess: "申請が正常に送信されました！",
    applicationError: "送信エラー"
  },
  ko: {
    badge: "인플루언서 프로그램",
    heroTitle: "되세요",
    heroTitleHighlight: "BidBlitz 파트너",
    heroDesc: "당신의 영향력으로 수익을 얻으세요! 인플루언서 프로그램에 참여하고 최대",
    commission: "30% 수수료",
    heroDescEnd: "팔로워의 모든 구매에서.",
    applyNow: "지금 신청",
    alreadyPartner: "이미 파트너? 로그인",
    maxCommission: "최대 수수료",
    activePartners: "활동 파트너",
    paidOut: "지급됨",
    activation: "활성화",
    benefitsTitle: "파트너로서의 혜택",
    benefit1Title: "최대 30% 수수료",
    benefit1Desc: "팔로워의 모든 구매에서 수익",
    benefit2Title: "독점 할인",
    benefit2Desc: "팔로워에게 5-10% 할인 제공",
    benefit3Title: "무료 입찰",
    benefit3Desc: "테스트용 월간 무료 입찰",
    benefit4Title: "VIP 상태",
    benefit4Desc: "독점 VIP 경매 접근",
    benefit5Title: "개인 대시보드",
    benefit5Desc: "수익 실시간 추적",
    benefit6Title: "보너스 프로그램",
    benefit6Desc: "목표 달성 시 추가 보너스",
    howItWorks: "작동 방식",
    step1Title: "신청",
    step1Desc: "양식 작성",
    step2Title: "활성화",
    step2Desc: "검토 후 계정 활성화",
    step3Title: "공유",
    step3Desc: "팔로워에게 BidBlitz 홍보",
    step4Title: "수익",
    step4Desc: "모든 구매에서 수수료 수령",
    becomePartner: "파트너 되기",
    name: "이름",
    email: "이메일",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "총 팔로워",
    followersPlaceholder: "예: 10,000",
    message: "메시지 (선택)",
    messagePlaceholder: "자기소개를 해주세요...",
    submit: "신청서 제출",
    submitting: "제출 중...",
    successTitle: "신청이 접수되었습니다!",
    successDesc: "관심 가져주셔서 감사합니다! 신청서를 검토하고 24-48시간 내에 연락드리겠습니다.",
    backToHome: "홈으로 돌아가기",
    yourName: "이름",
    yourEmail: "이메일",
    username: "@사용자명",
    channel: "채널",
    applicationSuccess: "신청이 성공적으로 전송되었습니다!",
    applicationError: "전송 오류"
  },
  hi: {
    badge: "इन्फ्लुएंसर प्रोग्राम",
    heroTitle: "बनें",
    heroTitleHighlight: "BidBlitz पार्टनर",
    heroDesc: "अपनी पहुंच से कमाएं! हमारे इन्फ्लुएंसर प्रोग्राम में शामिल हों और पाएं",
    commission: "30% कमीशन",
    heroDescEnd: "आपके फॉलोअर्स की सभी खरीदारी पर।",
    applyNow: "अभी आवेदन करें",
    alreadyPartner: "पहले से पार्टनर? लॉगिन",
    maxCommission: "अधिकतम कमीशन",
    activePartners: "सक्रिय पार्टनर",
    paidOut: "भुगतान किया",
    activation: "सक्रियण",
    benefitsTitle: "पार्टनर के रूप में आपके लाभ",
    benefit1Title: "30% तक कमीशन",
    benefit1Desc: "फॉलोअर्स की हर खरीदारी पर कमाएं",
    benefit2Title: "विशेष छूट",
    benefit2Desc: "फॉलोअर्स को 5-10% छूट दें",
    benefit3Title: "मुफ्त बोलियां",
    benefit3Desc: "परीक्षण के लिए मासिक मुफ्त बोलियां",
    benefit4Title: "VIP स्थिति",
    benefit4Desc: "विशेष VIP नीलामियों तक पहुंच",
    benefit5Title: "व्यक्तिगत डैशबोर्ड",
    benefit5Desc: "रियल-टाइम में कमाई ट्रैक करें",
    benefit6Title: "बोनस प्रोग्राम",
    benefit6Desc: "लक्ष्य पूरा करने पर अतिरिक्त बोनस",
    howItWorks: "यह कैसे काम करता है",
    step1Title: "आवेदन करें",
    step1Desc: "फॉर्म भरें",
    step2Title: "सक्रियण",
    step2Desc: "हम समीक्षा करें और खाता सक्रिय करें",
    step3Title: "साझा करें",
    step3Desc: "फॉलोअर्स को BidBlitz प्रमोट करें",
    step4Title: "कमाएं",
    step4Desc: "हर खरीदारी पर कमीशन पाएं",
    becomePartner: "पार्टनर बनें",
    name: "नाम",
    email: "ईमेल",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "कुल फॉलोअर्स",
    followersPlaceholder: "जैसे 10,000",
    message: "संदेश (वैकल्पिक)",
    messagePlaceholder: "अपने बारे में बताएं...",
    submit: "आवेदन जमा करें",
    submitting: "जमा हो रहा है...",
    successTitle: "आवेदन प्राप्त!",
    successDesc: "आपकी रुचि के लिए धन्यवाद! हम आवेदन की समीक्षा करेंगे और 24-48 घंटों में संपर्क करेंगे।",
    backToHome: "होम पर वापस",
    yourName: "आपका नाम",
    yourEmail: "आपका@email.com",
    username: "@यूजरनेम",
    channel: "चैनल",
    applicationSuccess: "आवेदन सफलतापूर्वक भेजा गया!",
    applicationError: "भेजने में त्रुटि"
  },
  cs: {
    badge: "Influencer Program",
    heroTitle: "Staňte se",
    heroTitleHighlight: "Partnerem BidBlitz",
    heroDesc: "Vydělávejte svým dosahem! Připojte se k programu influencerů a získejte až",
    commission: "30% Provizi",
    heroDescEnd: "ze všech nákupů vašich sledujících.",
    applyNow: "Přihlásit se",
    alreadyPartner: "Již partner? Přihlásit",
    maxCommission: "Max. Provize",
    activePartners: "Aktivních Partnerů",
    paidOut: "Vyplaceno",
    activation: "Aktivace",
    benefitsTitle: "Vaše Výhody jako Partner",
    benefit1Title: "Až 30% Provize",
    benefit1Desc: "Vydělávejte z každého nákupu sledujících",
    benefit2Title: "Exkluzivní Slevy",
    benefit2Desc: "Nabídněte sledujícím 5-10% slevu",
    benefit3Title: "Bezplatné Nabídky",
    benefit3Desc: "Měsíční bezplatné nabídky k testování",
    benefit4Title: "VIP Status",
    benefit4Desc: "Přístup k exkluzivním VIP aukcím",
    benefit5Title: "Osobní Dashboard",
    benefit5Desc: "Sledování výdělků v reálném čase",
    benefit6Title: "Bonusový Program",
    benefit6Desc: "Extra bonusy při dosažení cílů",
    howItWorks: "Jak to Funguje",
    step1Title: "Přihlaste se",
    step1Desc: "Vyplňte formulář",
    step2Title: "Aktivace",
    step2Desc: "Zkontrolujeme a aktivujeme váš účet",
    step3Title: "Sdílejte",
    step3Desc: "Propagujte BidBlitz sledujícím",
    step4Title: "Vydělávejte",
    step4Desc: "Získejte provizi za každý nákup",
    becomePartner: "Stát se Partnerem",
    name: "Jméno",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Celkem Sledujících",
    followersPlaceholder: "např. 10 000",
    message: "Zpráva (volitelné)",
    messagePlaceholder: "Řekněte nám více o sobě...",
    submit: "Odeslat Přihlášku",
    submitting: "Odesílání...",
    successTitle: "Přihláška Přijata!",
    successDesc: "Děkujeme za zájem! Přihlášku zkontrolujeme a ozveme se do 24-48 hodin.",
    backToHome: "Zpět na Hlavní",
    yourName: "Vaše jméno",
    yourEmail: "vas@email.cz",
    username: "@uzivatel",
    channel: "Kanál",
    applicationSuccess: "Přihláška úspěšně odeslána!",
    applicationError: "Chyba při odesílání"
  },
  sv: {
    badge: "Influencer-program",
    heroTitle: "Bli",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Tjäna pengar på din räckvidd! Gå med i vårt influencer-program och få upp till",
    commission: "30% Provision",
    heroDescEnd: "på alla köp från dina följare.",
    applyNow: "Ansök Nu",
    alreadyPartner: "Redan partner? Logga in",
    maxCommission: "Max. Provision",
    activePartners: "Aktiva Partners",
    paidOut: "Utbetalt",
    activation: "Aktivering",
    benefitsTitle: "Dina Fördelar som Partner",
    benefit1Title: "Upp till 30% Provision",
    benefit1Desc: "Tjäna på varje köp från följare",
    benefit2Title: "Exklusiva Rabatter",
    benefit2Desc: "Ge dina följare 5-10% rabatt",
    benefit3Title: "Gratis Bud",
    benefit3Desc: "Månatliga gratis bud för testning",
    benefit4Title: "VIP-status",
    benefit4Desc: "Tillgång till exklusiva VIP-auktioner",
    benefit5Title: "Personlig Dashboard",
    benefit5Desc: "Realtidsspårning av intäkter",
    benefit6Title: "Bonusprogram",
    benefit6Desc: "Extra bonusar vid måluppfyllelse",
    howItWorks: "Så Fungerar Det",
    step1Title: "Ansök",
    step1Desc: "Fyll i formuläret",
    step2Title: "Aktivering",
    step2Desc: "Vi granskar och aktiverar ditt konto",
    step3Title: "Dela",
    step3Desc: "Marknadsför BidBlitz till följare",
    step4Title: "Tjäna",
    step4Desc: "Få provision för varje köp",
    becomePartner: "Bli Partner",
    name: "Namn",
    email: "E-post",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Totalt Följare",
    followersPlaceholder: "t.ex. 10 000",
    message: "Meddelande (valfritt)",
    messagePlaceholder: "Berätta mer om dig själv...",
    submit: "Skicka Ansökan",
    submitting: "Skickar...",
    successTitle: "Ansökan Mottagen!",
    successDesc: "Tack för ditt intresse! Vi granskar din ansökan och kontaktar dig inom 24-48 timmar.",
    backToHome: "Tillbaka till Hem",
    yourName: "Ditt namn",
    yourEmail: "din@email.se",
    username: "@användare",
    channel: "Kanal",
    applicationSuccess: "Ansökan skickad!",
    applicationError: "Fel vid sändning"
  },
  da: {
    badge: "Influencer Program",
    heroTitle: "Bliv",
    heroTitleHighlight: "BidBlitz Partner",
    heroDesc: "Tjen penge på din rækkevidde! Deltag i vores influencer-program og modtag op til",
    commission: "30% Kommission",
    heroDescEnd: "på alle køb fra dine følgere.",
    applyNow: "Ansøg Nu",
    alreadyPartner: "Allerede partner? Log ind",
    maxCommission: "Maks. Kommission",
    activePartners: "Aktive Partnere",
    paidOut: "Udbetalt",
    activation: "Aktivering",
    benefitsTitle: "Dine Fordele som Partner",
    benefit1Title: "Op til 30% Kommission",
    benefit1Desc: "Tjen på hvert køb fra følgere",
    benefit2Title: "Eksklusive Rabatter",
    benefit2Desc: "Giv dine følgere 5-10% rabat",
    benefit3Title: "Gratis Bud",
    benefit3Desc: "Månedlige gratis bud til test",
    benefit4Title: "VIP Status",
    benefit4Desc: "Adgang til eksklusive VIP-auktioner",
    benefit5Title: "Personligt Dashboard",
    benefit5Desc: "Realtidssporing af indtjening",
    benefit6Title: "Bonusprogram",
    benefit6Desc: "Ekstra bonus ved målopfyldelse",
    howItWorks: "Sådan Fungerer Det",
    step1Title: "Ansøg",
    step1Desc: "Udfyld formularen",
    step2Title: "Aktivering",
    step2Desc: "Vi gennemgår og aktiverer din konto",
    step3Title: "Del",
    step3Desc: "Promover BidBlitz til følgere",
    step4Title: "Tjen",
    step4Desc: "Modtag kommission for hvert køb",
    becomePartner: "Bliv Partner",
    name: "Navn",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Totalt Følgere",
    followersPlaceholder: "f.eks. 10.000",
    message: "Besked (valgfrit)",
    messagePlaceholder: "Fortæl os mere om dig selv...",
    submit: "Send Ansøgning",
    submitting: "Sender...",
    successTitle: "Ansøgning Modtaget!",
    successDesc: "Tak for din interesse! Vi gennemgår din ansøgning og kontakter dig inden for 24-48 timer.",
    backToHome: "Tilbage til Hjem",
    yourName: "Dit navn",
    yourEmail: "din@email.dk",
    username: "@bruger",
    channel: "Kanal",
    applicationSuccess: "Ansøgning sendt!",
    applicationError: "Fejl ved afsendelse"
  },
  fi: {
    badge: "Vaikuttajaohjelma",
    heroTitle: "Tule",
    heroTitleHighlight: "BidBlitz Kumppaniksi",
    heroDesc: "Ansaitse tavoittavuudellasi! Liity vaikuttajaohjelmaamme ja saa jopa",
    commission: "30% Provisio",
    heroDescEnd: "kaikista seuraajiesi ostoksista.",
    applyNow: "Hae Nyt",
    alreadyPartner: "Jo kumppani? Kirjaudu",
    maxCommission: "Max. Provisio",
    activePartners: "Aktiivisia Kumppaneita",
    paidOut: "Maksettu",
    activation: "Aktivointi",
    benefitsTitle: "Etusi Kumppanina",
    benefit1Title: "Jopa 30% Provisio",
    benefit1Desc: "Ansaitse jokaisesta seuraajien ostosta",
    benefit2Title: "Eksklusiiviset Alennukset",
    benefit2Desc: "Tarjoa seuraajille 5-10% alennus",
    benefit3Title: "Ilmaiset Tarjoukset",
    benefit3Desc: "Kuukausittaiset ilmaiset tarjoukset testaukseen",
    benefit4Title: "VIP-status",
    benefit4Desc: "Pääsy eksklusiivisiin VIP-huutokauppoihin",
    benefit5Title: "Henkilökohtainen Dashboard",
    benefit5Desc: "Reaaliaikainen ansioiden seuranta",
    benefit6Title: "Bonusohjelma",
    benefit6Desc: "Lisäbonukset tavoitteiden saavuttamisesta",
    howItWorks: "Näin se Toimii",
    step1Title: "Hae",
    step1Desc: "Täytä lomake",
    step2Title: "Aktivointi",
    step2Desc: "Tarkistamme ja aktivoimme tilisi",
    step3Title: "Jaa",
    step3Desc: "Mainosta BidBlitziä seuraajille",
    step4Title: "Ansaitse",
    step4Desc: "Saa provisio jokaisesta ostosta",
    becomePartner: "Tule Kumppaniksi",
    name: "Nimi",
    email: "Sähköposti",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Seuraajia Yhteensä",
    followersPlaceholder: "esim. 10 000",
    message: "Viesti (valinnainen)",
    messagePlaceholder: "Kerro meille itsestäsi...",
    submit: "Lähetä Hakemus",
    submitting: "Lähetetään...",
    successTitle: "Hakemus Vastaanotettu!",
    successDesc: "Kiitos kiinnostuksestasi! Tarkistamme hakemuksesi ja otamme yhteyttä 24-48 tunnin kuluessa.",
    backToHome: "Takaisin Etusivulle",
    yourName: "Nimesi",
    yourEmail: "sinun@email.fi",
    username: "@käyttäjä",
    channel: "Kanava",
    applicationSuccess: "Hakemus lähetetty!",
    applicationError: "Virhe lähetyksessä"
  },
  el: {
    badge: "Πρόγραμμα Influencers",
    heroTitle: "Γίνε",
    heroTitleHighlight: "Συνεργάτης BidBlitz",
    heroDesc: "Κέρδισε χρήματα με την απήχησή σου! Εγγράψου στο πρόγραμμα influencers και λάβε έως",
    commission: "30% Προμήθεια",
    heroDescEnd: "σε όλες τις αγορές των ακολούθων σου.",
    applyNow: "Κάνε Αίτηση",
    alreadyPartner: "Ήδη συνεργάτης; Σύνδεση",
    maxCommission: "Μέγ. Προμήθεια",
    activePartners: "Ενεργοί Συνεργάτες",
    paidOut: "Πληρώθηκε",
    activation: "Ενεργοποίηση",
    benefitsTitle: "Τα Οφέλη σου ως Συνεργάτης",
    benefit1Title: "Έως 30% Προμήθεια",
    benefit1Desc: "Κέρδισε από κάθε αγορά ακολούθων",
    benefit2Title: "Αποκλειστικές Εκπτώσεις",
    benefit2Desc: "Προσφέρεις 5-10% έκπτωση στους ακόλουθους",
    benefit3Title: "Δωρεάν Προσφορές",
    benefit3Desc: "Μηνιαίες δωρεάν προσφορές για δοκιμή",
    benefit4Title: "VIP Status",
    benefit4Desc: "Πρόσβαση σε αποκλειστικές VIP δημοπρασίες",
    benefit5Title: "Προσωπικό Dashboard",
    benefit5Desc: "Παρακολούθηση κερδών σε πραγματικό χρόνο",
    benefit6Title: "Πρόγραμμα Bonus",
    benefit6Desc: "Έξτρα bonus στην επίτευξη στόχων",
    howItWorks: "Πώς Λειτουργεί",
    step1Title: "Κάνε Αίτηση",
    step1Desc: "Συμπλήρωσε τη φόρμα",
    step2Title: "Ενεργοποίηση",
    step2Desc: "Ελέγχουμε και ενεργοποιούμε τον λογαριασμό",
    step3Title: "Μοιράσου",
    step3Desc: "Προώθησε το BidBlitz στους ακόλουθους",
    step4Title: "Κέρδισε",
    step4Desc: "Λάβε προμήθεια για κάθε αγορά",
    becomePartner: "Γίνε Συνεργάτης",
    name: "Όνομα",
    email: "Email",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    followers: "Σύνολο Ακολούθων",
    followersPlaceholder: "π.χ. 10.000",
    message: "Μήνυμα (προαιρετικό)",
    messagePlaceholder: "Πες μας περισσότερα για σένα...",
    submit: "Υποβολή Αίτησης",
    submitting: "Αποστολή...",
    successTitle: "Η Αίτηση Ελήφθη!",
    successDesc: "Ευχαριστούμε για το ενδιαφέρον! Θα εξετάσουμε την αίτηση και θα επικοινωνήσουμε σε 24-48 ώρες.",
    backToHome: "Επιστροφή στην Αρχική",
    yourName: "Το όνομά σου",
    yourEmail: "email@sou.gr",
    username: "@χρήστης",
    channel: "Κανάλι",
    applicationSuccess: "Η αίτηση στάλθηκε επιτυχώς!",
    applicationError: "Σφάλμα αποστολής"
  }
};

export default function InfluencerBecome() {
  const { language , mappedLanguage } = useLanguage();
  // Use mappedLanguage for regional variants (e.g., xk -> sq)
  const langKey = mappedLanguage || language;
  const t = translations[langKey] || translations.de;
  
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  
  const [form, setForm] = useState({
    name: '',
    email: '',
    instagram: '',
    youtube: '',
    tiktok: '',
    followers: '',
    message: ''
  });
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    try {
      await axios.post(`${API}/influencer/apply`, form);
      setSubmitted(true);
      toast.success(t.applicationSuccess);
    } catch (error) {
      toast.error(error.response?.data?.detail || t.applicationError);
    } finally {
      setLoading(false);
    }
  };
  
  const benefits = [
    { icon: <DollarSign className="w-6 h-6" />, title: t.benefit1Title, desc: t.benefit1Desc },
    { icon: <Gift className="w-6 h-6" />, title: t.benefit2Title, desc: t.benefit2Desc },
    { icon: <Zap className="w-6 h-6" />, title: t.benefit3Title, desc: t.benefit3Desc },
    { icon: <Crown className="w-6 h-6" />, title: t.benefit4Title, desc: t.benefit4Desc },
    { icon: <Target className="w-6 h-6" />, title: t.benefit5Title, desc: t.benefit5Desc },
    { icon: <Award className="w-6 h-6" />, title: t.benefit6Title, desc: t.benefit6Desc }
  ];
  
  const steps = [
    { num: '1', title: t.step1Title, desc: t.step1Desc },
    { num: '2', title: t.step2Title, desc: t.step2Desc },
    { num: '3', title: t.step3Title, desc: t.step3Desc },
    { num: '4', title: t.step4Title, desc: t.step4Desc }
  ];
  
  if (submitted) {
    return (
      <div className="min-h-screen pt-24 pb-12 px-4 flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="w-24 h-24 rounded-full bg-gradient-to-br from-green-400 to-emerald-500 flex items-center justify-center mx-auto mb-6">
            <Check className="w-12 h-12 text-gray-800" />
          </div>
          <h1 className="text-3xl font-bold text-gray-800 mb-4">{t.successTitle}</h1>
          <p className="text-gray-500 mb-6">{t.successDesc}</p>
          <Link to="/">
            <Button className="bg-gradient-to-r from-cyan-500 to-cyan-600">
              {t.backToHome}
            </Button>
          </Link>
        </div>
      </div>
    );
  }
  
  return (
    <div className="min-h-screen pt-20 pb-12 bg-gradient-to-b from-slate-50 via-white to-amber-50/30" data-testid="influencer-become">
      {/* Hero Section - Improved Design */}
      <section className="relative overflow-hidden py-20 px-4">
        {/* Modern gradient background */}
        <div className="absolute inset-0 bg-gradient-to-br from-amber-100/60 via-orange-50/40 to-yellow-50/50" />
        <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-bl from-orange-300/20 to-transparent rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-gradient-to-tr from-amber-400/15 to-transparent rounded-full blur-3xl" />
        
        <div className="max-w-5xl mx-auto text-center relative z-10">
          <div className="inline-flex items-center gap-2 bg-gradient-to-r from-amber-500 to-orange-500 text-white px-5 py-2.5 rounded-full text-sm font-semibold mb-8 shadow-lg shadow-amber-500/25">
            <Star className="w-4 h-4" fill="currentColor" />
            {t.badge}
          </div>
          
          <h1 className="text-4xl md:text-6xl font-black text-slate-800 mb-6 tracking-tight">
            {t.heroTitle} <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-500 via-orange-500 to-amber-600">{t.heroTitleHighlight}</span>
          </h1>
          
          <p className="text-lg md:text-xl text-slate-600 mb-10 max-w-2xl mx-auto leading-relaxed">
            {t.heroDesc} <span className="text-amber-600 font-bold">{t.commission}</span> {t.heroDescEnd}
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              onClick={() => setShowForm(true)}
              className="bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-white font-bold px-10 py-4 text-lg rounded-xl shadow-lg shadow-amber-500/30 transition-all hover:scale-105"
            >
              <Star className="w-5 h-5 mr-2" fill="currentColor" />
              {t.applyNow}
            </Button>
            <Link to="/influencer-login">
              <Button variant="outline" className="border-2 border-slate-300 text-slate-700 hover:bg-slate-100 hover:border-slate-400 px-10 py-4 text-lg rounded-xl transition-all">
                {t.alreadyPartner}
              </Button>
            </Link>
          </div>
        </div>
      </section>
      
      {/* Stats - Improved Cards */}
      <section className="py-14 px-4">
        <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-5">
          <div className="bg-white rounded-2xl p-6 text-center shadow-lg shadow-slate-200/50 border border-slate-100 hover:shadow-xl transition-shadow">
            <p className="text-4xl font-black bg-gradient-to-r from-amber-500 to-orange-500 bg-clip-text text-transparent">30%</p>
            <p className="text-slate-500 text-sm font-medium mt-1">{t.maxCommission}</p>
          </div>
          <div className="bg-white rounded-2xl p-6 text-center shadow-lg shadow-slate-200/50 border border-slate-100 hover:shadow-xl transition-shadow">
            <p className="text-4xl font-black text-cyan-500">50+</p>
            <p className="text-slate-500 text-sm font-medium mt-1">{t.activePartners}</p>
          </div>
          <div className="bg-white rounded-2xl p-6 text-center shadow-lg shadow-slate-200/50 border border-slate-100 hover:shadow-xl transition-shadow">
            <p className="text-4xl font-black text-emerald-500">€10K+</p>
            <p className="text-slate-500 text-sm font-medium mt-1">{t.paidOut}</p>
          </div>
          <div className="bg-white rounded-2xl p-6 text-center shadow-lg shadow-slate-200/50 border border-slate-100 hover:shadow-xl transition-shadow">
            <p className="text-4xl font-black text-violet-500">24h</p>
            <p className="text-slate-500 text-sm font-medium mt-1">{t.activation}</p>
          </div>
        </div>
      </section>
      
      {/* Benefits - Modern Cards */}
      <section className="py-16 px-4 bg-gradient-to-b from-white via-slate-50/50 to-amber-50/30">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-800 text-center mb-14">
            {t.benefitsTitle}
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {benefits.map((benefit, index) => (
              <div key={index} className="bg-white rounded-2xl p-7 shadow-lg shadow-slate-200/40 border border-slate-100 hover:shadow-xl hover:border-amber-200 transition-all group">
                <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-amber-100 to-orange-100 flex items-center justify-center text-amber-600 mb-5 group-hover:scale-110 transition-transform">
                  {benefit.icon}
                </div>
                <h3 className="text-lg font-bold text-slate-800 mb-2">{benefit.title}</h3>
                <p className="text-slate-500 leading-relaxed">{benefit.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* How it works - Modern Steps */}
      <section className="py-16 px-4">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-800 text-center mb-14">
            {t.howItWorks}
          </h2>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="text-center group">
                <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-amber-500 to-orange-500 flex items-center justify-center text-3xl font-black text-white mx-auto mb-5 shadow-lg shadow-amber-500/30 group-hover:scale-110 transition-transform">
                  {step.num}
                </div>
                <h3 className="text-lg font-bold text-slate-800 mb-2">{step.title}</h3>
                <p className="text-slate-500 text-sm">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Application Form - Premium Design */}
      {showForm && (
        <section id="apply" className="py-16 px-4">
          <div className="max-w-xl mx-auto">
            <div className="bg-white rounded-3xl p-8 md:p-10 shadow-2xl shadow-slate-200/60 border border-slate-100">
              <h2 className="text-2xl font-bold text-slate-800 mb-8 flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-500 to-orange-500 flex items-center justify-center">
                  <Star className="w-5 h-5 text-white" fill="white" />
                </div>
                {t.becomePartner}
              </h2>
              
              <form onSubmit={handleSubmit} className="space-y-5">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-slate-700 font-medium">{t.name} *</Label>
                    <Input
                      value={form.name}
                      onChange={(e) => setForm({...form, name: e.target.value})}
                      placeholder={t.yourName}
                      className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400 focus:ring-amber-400"
                      required
                    />
                  </div>
                  <div>
                    <Label className="text-slate-700 font-medium">{t.email} *</Label>
                    <Input
                      type="email"
                      value={form.email}
                      onChange={(e) => setForm({...form, email: e.target.value})}
                      placeholder={t.yourEmail}
                      className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400 focus:ring-amber-400"
                      required
                    />
                  </div>
                </div>
                
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <Label className="text-slate-700 font-medium flex items-center gap-1">
                      <Instagram className="w-4 h-4 text-pink-500" /> {t.instagram}
                    </Label>
                    <Input
                      value={form.instagram}
                      onChange={(e) => setForm({...form, instagram: e.target.value})}
                      placeholder={t.username}
                      className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400"
                    />
                  </div>
                  <div>
                    <Label className="text-slate-700 font-medium flex items-center gap-1">
                      <Youtube className="w-4 h-4 text-red-500" /> {t.youtube}
                    </Label>
                    <Input
                      value={form.youtube}
                      onChange={(e) => setForm({...form, youtube: e.target.value})}
                      placeholder={t.channel}
                      className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400"
                    />
                  </div>
                  <div>
                    <Label className="text-slate-700 font-medium">{t.tiktok}</Label>
                    <Input
                      value={form.tiktok}
                      onChange={(e) => setForm({...form, tiktok: e.target.value})}
                      placeholder={t.username}
                      className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400"
                    />
                  </div>
                </div>
                
                <div>
                  <Label className="text-slate-700 font-medium">{t.followers} *</Label>
                  <Input
                    value={form.followers}
                    onChange={(e) => setForm({...form, followers: e.target.value})}
                    placeholder={t.followersPlaceholder}
                    className="bg-slate-50 border-slate-200 text-slate-800 focus:border-amber-400"
                    required
                  />
                </div>
                
                <div>
                  <Label className="text-slate-700 font-medium">{t.message}</Label>
                  <textarea
                    value={form.message}
                    onChange={(e) => setForm({...form, message: e.target.value})}
                    placeholder={t.messagePlaceholder}
                    className="w-full bg-slate-50 border border-slate-200 text-slate-800 rounded-lg p-3 h-28 resize-none focus:border-amber-400 focus:ring-1 focus:ring-amber-400 focus:outline-none"
                  />
                </div>
                
                <Button
                  type="submit"
                  disabled={loading || !form.name || !form.email || !form.followers}
                  className="w-full py-4 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-white font-bold text-lg rounded-xl shadow-lg shadow-amber-500/30 transition-all hover:scale-[1.02]"
                >
                  {loading ? t.submitting : t.submit}
                </Button>
              </form>
            </div>
          </div>
        </section>
      )}
    </div>
  );
}
