/**
 * Scooter/Mobility Translations - shared by all mobility pages
 */
const mobilityTranslations = {
  scooterGuide: {
    de: {hero:"So funktioniert BidBlitz Mobility",heroSub:"E-Scooter und E-Bikes mieten - einfach, günstig und umweltfreundlich",stepsTitle:"In 5 Schritten losfahren",s1:"Wallet aufladen",s1d:"Laden Sie Ihr BidBlitz Wallet auf. Entsperrgebühr: 1€, danach 0,25€/Min.",s2:"Scooter finden",s2d:"Öffnen Sie die Scooter-App und sehen Sie verfügbare Scooter auf der Karte.",s3:"QR-Code scannen",s3d:"Scannen Sie den QR-Code am Scooter oder geben Sie die Seriennummer ein.",s4:"Losfahren",s4d:"Nach der Entsperrung können Sie sofort losfahren. Timer und Kosten laufen automatisch.",s5:"Fahrt beenden",s5d:"Drücken Sie 'Fahrt beenden' in der App. Parken Sie ordentlich.",prices:"Preise",unlock:"Entsperrgebühr",perMin:"Pro Minute",freeRes:"Reservierung: 10 Minuten kostenlos",safety:"Sicherheitsregeln",r1:"Fahren Sie auf Radwegen oder Straßen, nicht auf Gehwegen",r2:"Maximale Geschwindigkeit: 20 km/h",r3:"Helm wird empfohlen (Pflicht unter 18)",r4:"Nicht zu zweit auf einem Scooter",r5:"Nicht unter Alkohol- oder Drogeneinfluss",r6:"Ordentlich parken, keine Wege blockieren",r7:"Mindestalter: 18 Jahre",problem:"Problem mit einem Scooter?",problemD:"Melden Sie defekte Scooter direkt in der App.",contact:"Support kontaktieren",cta:"Jetzt Scooter finden"},
    en: {hero:"How BidBlitz Mobility Works",heroSub:"Rent e-scooters and e-bikes - simple, affordable and eco-friendly",stepsTitle:"Get Started in 5 Steps",s1:"Top up Wallet",s1d:"Top up your BidBlitz Wallet. Unlock: €1, then €0.25/min.",s2:"Find a Scooter",s2d:"Open the Scooter App and see available scooters on the map.",s3:"Scan QR Code",s3d:"Scan the QR code or enter the serial number.",s4:"Start Riding",s4d:"After unlocking, ride immediately. Timer starts automatically.",s5:"End Ride",s5d:"Press 'End Ride' in the app. Park properly.",prices:"Prices",unlock:"Unlock Fee",perMin:"Per Minute",freeRes:"Reservation: 10 minutes free",safety:"Safety Rules",r1:"Ride on bike lanes or roads, not sidewalks",r2:"Maximum speed: 20 km/h",r3:"Helmet recommended (required under 18)",r4:"No two people on one scooter",r5:"No riding under influence",r6:"Park properly, don't block pathways",r7:"Minimum age: 18",problem:"Problem with a scooter?",problemD:"Report defective scooters in the app.",contact:"Contact Support",cta:"Find a Scooter"},
    sq: {hero:"Si Funksionon BidBlitz Mobility",heroSub:"Merr me qira e-scooter - thjesht dhe miqësor",stepsTitle:"Fillo në 5 Hapa",s1:"Mbush Wallet-in",s1d:"Mbushni Wallet-in tuaj. Hapja: 1€, pastaj 0,25€/min.",s2:"Gjej një Scooter",s2d:"Hapni aplikacionin dhe shikoni scooterët në hartë.",s3:"Skanoni Kodin QR",s3d:"Skanoni kodin QR ose shkruani numrin serial.",s4:"Fillo Udhëtimin",s4d:"Pas hapjes filloni menjëherë. Kohëmatësi fillon automatikisht.",s5:"Përfundo Udhëtimin",s5d:"Shtypni 'Përfundo' në aplikacion. Parkoni siç duhet.",prices:"Çmimet",unlock:"Tarifa e Hapjes",perMin:"Për Minutë",freeRes:"Rezervimi: 10 minuta falas",safety:"Rregullat e Sigurisë",r1:"Vozitni në shteg biçikletash, jo në trotuar",r2:"Shpejtësia maksimale: 20 km/h",r3:"Helmeta rekomandohet",r4:"Mos vozitni dy persona në një scooter",r5:"Mos vozitni nën ndikimin e alkoolit",r6:"Parkoni siç duhet",r7:"Mosha minimale: 18 vjeç",problem:"Problem me një scooter?",problemD:"Raportoni scooterët e dëmtuar në aplikacion.",contact:"Kontakto Mbështetjen",cta:"Gjej një Scooter"},
    tr: {hero:"BidBlitz Mobility Nasıl Çalışır",heroSub:"E-scooter kiralayın - basit ve çevre dostu",stepsTitle:"5 Adımda Başlayın",s1:"Cüzdanı Yükle",s1d:"Cüzdanınızı yükleyin. Kilit açma: 1€, sonra 0,25€/dk.",s2:"Scooter Bul",s2d:"Uygulamayı açın ve haritada scooterları görün.",s3:"QR Kodu Tara",s3d:"QR kodunu tarayın veya seri numarasını girin.",s4:"Sürmeye Başla",s4d:"Kilidi açtıktan sonra hemen sürün. Sayaç otomatik başlar.",s5:"Sürüşü Bitir",s5d:"Uygulamada 'Bitir' düğmesine basın. Düzgün park edin.",prices:"Fiyatlar",unlock:"Kilit Açma",perMin:"Dakika Başı",freeRes:"Rezervasyon: 10 dk ücretsiz",safety:"Güvenlik Kuralları",r1:"Bisiklet yollarında sürün",r2:"Maks hız: 20 km/h",r3:"Kask önerilir",r4:"Bir scooter'da iki kişi sürmeyin",r5:"Alkol etkisinde sürmeyin",r6:"Düzgün park edin",r7:"Min yaş: 18",problem:"Sorun mu var?",problemD:"Arızalı scooterları uygulamada bildirin.",contact:"Destek",cta:"Scooter Bul"},
    fr: {hero:"Comment Fonctionne BidBlitz Mobility",heroSub:"Louez des trottinettes électriques - simple et écologique",stepsTitle:"Commencez en 5 Étapes",s1:"Rechargez le Wallet",s1d:"Rechargez votre Wallet. Déverrouillage: 1€, puis 0,25€/min.",s2:"Trouvez une Trottinette",s2d:"Ouvrez l'app et voyez les trottinettes sur la carte.",s3:"Scannez le QR Code",s3d:"Scannez le QR code ou entrez le numéro de série.",s4:"Roulez",s4d:"Après déverrouillage, roulez immédiatement.",s5:"Terminez",s5d:"Appuyez sur 'Terminer'. Garez-vous correctement.",prices:"Tarifs",unlock:"Déverrouillage",perMin:"Par Minute",freeRes:"Réservation: 10 min gratuites",safety:"Règles de Sécurité",r1:"Roulez sur les pistes cyclables",r2:"Vitesse max: 20 km/h",r3:"Casque recommandé",r4:"Pas deux personnes sur une trottinette",r5:"Pas sous influence d'alcool",r6:"Garez-vous correctement",r7:"Âge min: 18 ans",problem:"Problème?",problemD:"Signalez dans l'appli.",contact:"Support",cta:"Trouver une Trottinette"},
  },
  haendlerFinder: {
    de: {title:"Händler-Finder",subtitle:"Partner-Geschäfte in deiner Nähe",search:"Händler suchen...",all:"Alle",found:"Händler gefunden",scooterP:"mit Scooter-Parkplatz",become:"Händler werden?",becomeD:"Registrieren Sie Ihr Geschäft als BidBlitz Partner.",apply:"Jetzt bewerben",route:"Route",call:"Anrufen",voucher:"GUTSCHEIN"},
    en: {title:"Merchant Finder",subtitle:"Partner stores near you",search:"Search merchants...",all:"All",found:"merchants found",scooterP:"with scooter parking",become:"Become a merchant?",becomeD:"Register your business as a BidBlitz Partner.",apply:"Apply now",route:"Route",call:"Call",voucher:"VOUCHER"},
    sq: {title:"Gjej Tregtarë",subtitle:"Dyqane partnerë pranë teje",search:"Kërko...",all:"Të gjitha",found:"tregtarë",scooterP:"me parkim scooteri",become:"Bëhu tregtar?",becomeD:"Regjistro biznesin si Partner.",apply:"Apliko",route:"Rruga",call:"Thirr",voucher:"KUPON"},
    tr: {title:"İşletme Bulucu",subtitle:"Yakınındaki partner işletmeler",search:"İşletme ara...",all:"Tümü",found:"işletme",scooterP:"scooter parkı",become:"İşletme ol?",becomeD:"İşletmenizi Partner olarak kaydedin.",apply:"Başvur",route:"Yol tarifi",call:"Ara",voucher:"KUPON"},
    fr: {title:"Trouver un Commerce",subtitle:"Commerces partenaires",search:"Chercher...",all:"Tous",found:"commerces",scooterP:"parking trottinette",become:"Devenir partenaire?",becomeD:"Inscrivez votre commerce.",apply:"Postuler",route:"Itinéraire",call:"Appeler",voucher:"BON"},
  },
  supportTickets: {
    de: {title:"Meine Tickets",count:"Anfragen",create:"Neues Ticket",createTitle:"Neues Support-Ticket",category:"Kategorie",subject:"Betreff",subjectPh:"Kurze Beschreibung",message:"Nachricht",messagePh:"Beschreiben Sie Ihr Anliegen...",submit:"Ticket erstellen",back:"Zurück",noTickets:"Keine Tickets vorhanden",noTicketsD:"Erstellen Sie ein Ticket bei Fragen",reply:"Nachricht schreiben...",general:"Allgemein",billing:"Abrechnung",device:"Gerät / Scooter",account:"Mein Konto",auction:"Auktion",other:"Sonstiges"},
    en: {title:"My Tickets",count:"requests",create:"New Ticket",createTitle:"New Support Ticket",category:"Category",subject:"Subject",subjectPh:"Brief description",message:"Message",messagePh:"Describe your issue...",submit:"Create Ticket",back:"Back",noTickets:"No tickets",noTicketsD:"Create a ticket for questions",reply:"Write a message...",general:"General",billing:"Billing",device:"Device / Scooter",account:"My Account",auction:"Auction",other:"Other"},
    sq: {title:"Tiketat e Mia",count:"kërkesa",create:"Tiketë e Re",createTitle:"Tiketë e Re",category:"Kategoria",subject:"Subjekti",subjectPh:"Përshkrim i shkurtër",message:"Mesazhi",messagePh:"Përshkruaj problemin...",submit:"Krijo Tiketën",back:"Kthehu",noTickets:"Nuk ka tiketa",noTicketsD:"Krijoni një tiketë",reply:"Shkruaj mesazh...",general:"Përgjithshme",billing:"Faturimi",device:"Pajisja",account:"Llogaria",auction:"Ankandi",other:"Tjetër"},
    tr: {title:"Biletlerim",count:"talep",create:"Yeni Bilet",createTitle:"Yeni Destek Bileti",category:"Kategori",subject:"Konu",subjectPh:"Kısa açıklama",message:"Mesaj",messagePh:"Sorununuzu açıklayın...",submit:"Bilet Oluştur",back:"Geri",noTickets:"Bilet yok",noTicketsD:"Sorular için bilet oluşturun",reply:"Mesaj yaz...",general:"Genel",billing:"Faturalama",device:"Cihaz",account:"Hesabım",auction:"Açık Artırma",other:"Diğer"},
    fr: {title:"Mes Tickets",count:"demandes",create:"Nouveau Ticket",createTitle:"Nouveau Ticket",category:"Catégorie",subject:"Sujet",subjectPh:"Description brève",message:"Message",messagePh:"Décrivez votre problème...",submit:"Créer",back:"Retour",noTickets:"Pas de tickets",noTicketsD:"Créez un ticket",reply:"Écrire...",general:"Général",billing:"Facturation",device:"Appareil",account:"Mon Compte",auction:"Enchère",other:"Autre"},
  },
  groupRides: {
    de: {title:"Gruppen-Fahrten",subtitle:"Fahr zusammen mit Freunden",createGroup:"Gruppe erstellen",joinGroup:"Gruppe beitreten",enterCode:"Gruppen-Code eingeben",iPayForAll:"Ich zahle für alle",iPayD:"Alle Fahrten von deinem Wallet",everyonePays:"Jeder zahlt selbst",everyoneD:"Jeder zahlt seine eigene Fahrt",payMode:"Wer zahlt?",back:"Zurück",members:"Mitglieder",leave:"Gruppe verlassen",disband:"Gruppe auflösen",shareCode:"Code teilen",howTitle:"So funktioniert es",how1:"Erstelle eine Gruppe und teile den Code",how2:"Freunde treten bei (max. 5)",how3:"Jeder mietet einen eigenen Scooter",how4:"Leader zahlt oder jeder selbst",inviteMax:"Lade bis zu 5 Freunde ein",leaderPays:"Leader zahlt"},
    en: {title:"Group Rides",subtitle:"Ride together with friends",createGroup:"Create Group",joinGroup:"Join Group",enterCode:"Enter group code",iPayForAll:"I pay for everyone",iPayD:"All rides from your wallet",everyonePays:"Everyone pays",everyoneD:"Each member pays their ride",payMode:"Who pays?",back:"Back",members:"Members",leave:"Leave Group",disband:"Disband",shareCode:"Share code",howTitle:"How it works",how1:"Create a group and share the code",how2:"Friends join (max 5)",how3:"Everyone rents their own scooter",how4:"Leader pays or everyone pays",inviteMax:"Invite up to 5 friends",leaderPays:"Leader pays"},
    sq: {title:"Udhëtime Grupore",subtitle:"Vozit me miqtë",createGroup:"Krijo Grup",joinGroup:"Bashkohu",enterCode:"Shkruaj kodin",iPayForAll:"Unë paguaj",iPayD:"Udhëtimet nga wallet-i yt",everyonePays:"Secili paguan",everyoneD:"Secili paguan vetë",payMode:"Kush paguan?",back:"Kthehu",members:"Anëtarët",leave:"Largohu",disband:"Shpërbëj",shareCode:"Ndaj kodin",howTitle:"Si funksionon",how1:"Krijo grup dhe ndaj kodin",how2:"Miqtë bashkohen (max 5)",how3:"Secili merr scooterin e vet",how4:"Lideri ose secili paguan",inviteMax:"Fto deri 5 miq",leaderPays:"Lideri paguan"},
    tr: {title:"Grup Sürüşleri",subtitle:"Arkadaşlarla birlikte",createGroup:"Grup Oluştur",joinGroup:"Gruba Katıl",enterCode:"Grup kodunu gir",iPayForAll:"Ben ödüyorum",iPayD:"Sürüşler cüzdanından",everyonePays:"Herkes öder",everyoneD:"Her üye kendi öder",payMode:"Kim öder?",back:"Geri",members:"Üyeler",leave:"Ayrıl",disband:"Dağıt",shareCode:"Kodu paylaş",howTitle:"Nasıl çalışır",how1:"Grup oluştur ve kodu paylaş",how2:"Arkadaşlar katılır (max 5)",how3:"Herkes kendi scooterını kiralar",how4:"Lider veya herkes öder",inviteMax:"5 arkadaş davet et",leaderPays:"Lider öder"},
    fr: {title:"Courses en Groupe",subtitle:"Roulez entre amis",createGroup:"Créer Groupe",joinGroup:"Rejoindre",enterCode:"Entrez le code",iPayForAll:"Je paie pour tous",iPayD:"Courses de votre wallet",everyonePays:"Chacun paie",everyoneD:"Chacun paie sa course",payMode:"Qui paie?",back:"Retour",members:"Membres",leave:"Quitter",disband:"Dissoudre",shareCode:"Partager le code",howTitle:"Comment ça marche",how1:"Créez un groupe et partagez",how2:"Les amis rejoignent (max 5)",how3:"Chacun loue sa trottinette",how4:"Le leader ou chacun paie",inviteMax:"Invitez 5 amis",leaderPays:"Le leader paie"},
  }
};

export function useMobilityTranslation(page, language) {
  const lang = language === 'xk' ? 'sq' : language;
  const pageTexts = mobilityTranslations[page];
  if (!pageTexts) return mobilityTranslations.scooterGuide?.de || {};
  return pageTexts[lang] || pageTexts.de || {};
}

export default mobilityTranslations;
